Repository red-hat-storage/rook, pull requests merged in 2019-11, with the labels that each got.

#6 resync with release 1.1
  Documentation/ceph-object-bucket-claim.md
  Documentation/ceph-object.md
  Documentation/ceph-upgrade.md
  Documentation/helm-operator.md
  cluster/charts/rook-ceph/templates/deployment.yaml
  cluster/examples/coreos/after-reboot-daemonset.yaml
  cluster/examples/coreos/before-reboot-daemonset.yaml
  cluster/examples/kubernetes/cassandra/operator.yaml
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  cluster/examples/kubernetes/ceph/toolbox.yaml
  cluster/examples/kubernetes/cockroachdb/operator.yaml
  cluster/examples/kubernetes/edgefs/operator.yaml
  cluster/examples/kubernetes/minio/operator.yaml
  cluster/examples/kubernetes/nfs/operator.yaml
  cluster/examples/kubernetes/yugabytedb/operator.yaml
  images/ceph/Makefile
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
Labels: size/L

#7 CSI: Create CSIDriver Object
  Documentation/ceph-upgrade.md
  cluster/charts/rook-ceph/templates/clusterrole.yaml
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  pkg/operator/ceph/csi/spec.go
  tests/framework/installer/ceph_manifests.go
Labels: size/M

#8 Merge the latest fixes from the release-1.1 branch
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/disruption/clusterdisruption/location.go
  pkg/operator/ceph/object/user/controller.go
  tests/integration/ceph_base_object_test.go
  tests/integration/ceph_mon_test.go
Labels: size/L

#11 Sync Release 1.1
  pkg/daemon/ceph/osd/volume.go
Labels: size/XS

#13 CSI: Make attach mandatory in ceph CSIDriver object
  Documentation/ceph-upgrade.md
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: size/M

#14 Resync Release 1.1
  Documentation/ceph-cluster-crd.md
  cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
Labels: size/L

#16 Resync Release 1.1
  Documentation/ceph-upgrade.md
  Documentation/helm-operator.md
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/version/version.go
  pkg/operator/ceph/version/version_test.go
Labels: size/L
