Repository red-hat-storage/rook, pull requests merged in 2019-12, with the labels that each got.

#19 CSI: Ability to disable snapshotter from ceph-csi rbd
  Documentation/helm-operator.md
  cluster/charts/rook-ceph/templates/deployment.yaml
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: lgtm, size/S

#20 ceph: continue orchestration on osd update errors
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/osd/osd.go
Labels: size/S

#21 Backport: Added OSD utilization alerts
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: size/S

#22 ceph: rgw change the liveness probe url
  pkg/operator/ceph/object/spec.go
Labels: size/XS

#23 ceph: only set isUpgrade when the image changes
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/cluster/controller.go
Labels: size/S
