Repository red-hat-storage/rook, pull requests merged in 2020-01, with the labels that each got.

#25 Continue with ceph upgrades even if the cluster is unhealthy
  Documentation/ceph-cluster-crd.md
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
  cluster/examples/kubernetes/ceph/cluster-test.yaml
  cluster/examples/kubernetes/ceph/cluster.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/cluster/osd/status_test.go
  pkg/operator/ceph/cluster/rbd/mirror.go
  pkg/operator/ceph/file/mds/mds.go
  pkg/operator/ceph/nfs/nfs.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/k8sutil/deployment.go
  pkg/operator/k8sutil/test/deployment.go
Labels: size/L

#26 CSI driver fix to support upgrades from OCP 4.2 to 4.3
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: do-not-merge/hold, size/M

#28 Rsync release 1.2
  cluster/examples/kubernetes/ceph/filesystem-ec.yaml
  cluster/examples/kubernetes/ceph/filesystem.yaml
  cmd/rook/ceph/osd_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/crash/reconcile.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/file/mds/mds.go
  pkg/operator/ceph/spec/label.go
  pkg/operator/ceph/version/version.go
Labels: size/L

#30 Release 1.2
  pkg/operator/ceph/cluster/crash/reconcile.go
Labels: size/XS

#31 Revert "backport of https://github.com/rook/rook/pull/4726 (update cephcsi to v2.0.0)"
  Documentation/ceph-block.md
  Documentation/ceph-csi-drivers.md
  Documentation/ceph-examples.md
  Documentation/ceph-upgrade.md
  Documentation/helm-operator.md
  cluster/charts/rook-ceph/templates/deployment.yaml
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  cluster/examples/kubernetes/ceph/csi/cephfs/storageclass.yaml
  cluster/examples/kubernetes/ceph/csi/rbd/storageclass-ec.yaml
  cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
  cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  cluster/examples/kubernetes/ceph/upgrade-from-v1.2-apply.yaml
  pkg/operator/ceph/csi/spec.go
  tests/framework/installer/ceph_manifests.go
Labels: size/L

#33 Enable Ceph-CSI 2.0 by default
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/spec.go
Labels: size/M
