Repository red-hat-storage/rook, pull requests merged in 2020-09, with the labels that each got.

#121 Bug 1878853: ceph: fix to support TLS enabled rgw-endpoint
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#120 Bug 1876852: ceph: fix to support TLS enabled rgw-endpoint
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#122 Revert "Bug 1876852: ceph: fix to support TLS enabled rgw-endpoint"
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#124 Bug 1879919: ceph: only run version check for monitoring
  pkg/operator/ceph/cluster/cluster_external.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#125 Bug 1873118: Backport mon pv cleanup
  build/makelib/golang.mk
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/node_test.go
  pkg/operator/ceph/cluster/mon/service.go
  pkg/operator/ceph/cluster/mon/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#127 Bug 1871875: Detect OSDs on PVCs in batches instead of with label selectors individually
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/osd.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#128 Bug 1883927: ceph: disable keyring after opening encrypted block
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/severity-urgent, bugzilla/valid-bug
