Repository red-hat-storage/rook, pull requests merged in 2020-08, with the labels that each got.

#95 Bug 1862133: ceph: bunch of fixes for create-external-cluster-resources.py
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#99 BUG 1867092: ceph: set pod anti affinity to provisioner pod
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util.go
  pkg/operator/k8sutil/deployment.go
  pkg/operator/k8sutil/statefulset.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#101 Bug 1867130: ceph: fix healtcheck for external cluster
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#102 Bug 1867998: ceph: do not validate default.rgw.buckets.index
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#104 Bug 1866812: ceph: check for gone node on crash collector
  pkg/operator/ceph/cluster/crash/reconcile.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#105 Bug 1862133: Making RBD provisioner, Ceph provisioner and Ceph node optional
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#109 Bug 1872680: ceph: fix mon endpoints split when using external ceph hosts
  images/ceph/toolbox.sh
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#111 Bug 1872589: ceph: run obc requests with debug and fix dns endpoint name for proxy env
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/s3-handlers.go
  pkg/operator/ceph/object/bucket/util.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#112 Bug 1872671: ceph: fix rebasing error
  pkg/operator/ceph/object/bucket/s3-handlers.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#113 Bug 1872589: ceph: fix unit test
  pkg/operator/ceph/object/bucket/provisionner_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high
