Repository red-hat-storage/rook, pull requests merged in 2020-10, with the labels that each got.

#126 Bug 1883398: ceph: update csi sidecar images
  Documentation/ceph-upgrade.md
  Documentation/helm-operator.md
  cluster/charts/rook-ceph/templates/clusterrole.yaml
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  pkg/operator/ceph/csi/spec.go
  tests/framework/installer/ceph_manifests.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#130 Bug 1885175: ceph: check underlaying block status
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#132 Bug 1885428: ceph: prevent closing of channel more than once
  pkg/operator/ceph/cluster/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#133 Bug 1885971: ceph: reduce s3 max retry
  pkg/operator/ceph/object/s3-handlers.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#134 Bug 1881071: ceph: adding '--upgrade' option to the script
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#136 BUG 1882277: ceph: remove owner reference set by rook on csidriver
  cluster/charts/rook-ceph/templates/clusterrole.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  pkg/operator/ceph/csi/spec.go
  tests/framework/installer/ceph_manifests.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#135 BUG 1888545: ceph: remove owner reference set by rook on csidriver
  cluster/charts/rook-ceph/templates/clusterrole.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  pkg/operator/ceph/csi/spec.go
  tests/framework/installer/ceph_manifests.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#137 Bug 1888713: ceph: fix mon pdb reconcile
  pkg/operator/ceph/disruption/clusterdisruption/mon.go
  pkg/operator/ceph/disruption/clusterdisruption/mon_test.go
  pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#139 Bug 1889866: Check for orphaned mon resources with every reconcile
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#140 Bug 1891874: ceph: fix mon pdb reconcile
  pkg/operator/ceph/disruption/clusterdisruption/mon.go
  pkg/operator/ceph/disruption/clusterdisruption/mon_test.go
  pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high
