Repository red-hat-storage/rook, pull requests merged in 2020-06, with the labels that each got.

#67 Bug 1848184: Handle node failure more gracefully (bp to release-4.4)
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/osd/health.go
  pkg/operator/ceph/cluster/osd/health_test.go
  pkg/operator/k8sutil/pod.go
Labels: bugzilla/severity-high, bugzilla/valid-bug

#73 Bug 1851311: Set the minimum rgw PGs for the metadata pools to the smaller default
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/operator/ceph/config/monstore.go
  pkg/operator/ceph/object/objectstore.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#74 Bug 1848184: Force delete mons in every reconcile and delay watching CRDs for first reconcile
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/mon/mon.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#76 Bug 1849723: ceph: added PVC utilization alerts
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-high
