Repository red-hat-storage/rook, pull requests merged in 2020-07, with the labels that each got.

#78 Bug 1849723: Revert "ceph: added PVC utilization alerts"
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/severity-high, bugzilla/valid-bug

#79 Bug 1852852: Capture logging from the osd daemon
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/config/defaults.go
  pkg/operator/ceph/controller/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#80 Bug 1840729: Reduce osd upgrade timeout from 10 minutes to one minute
  pkg/daemon/ceph/client/upgrade.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#81 Bug 1852983: Require rgw pods to be running to create object users
  pkg/operator/ceph/object/user/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#83 Bug 1850704: ceph: add http dial to verify external endpoint
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#82 Bug 1852983: Revert "ceph: require rgw pods to be running to create object users"
  pkg/operator/ceph/object/user/controller.go
Labels: bugzilla/severity-urgent, bugzilla/valid-bug

#84 Bug 1856414: ceph: report error on timeout
  pkg/daemon/ceph/client/status.go
  pkg/operator/ceph/cluster/cephstatus.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#90 Bug 1857304: ceph: make rgw option on external script
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#92 Bug 1859730: ceph: skip csi version detect if allowunsupported is set
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#93 Bug 1857304: ceph: make 'rgw_endpoint' check/validation also optional
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high
