Repository red-hat-storage/rook, pull requests merged in 2021-02, with the labels that each got.

#159 Bug 1924211: Shorten the name of the log-collector container to unblock installing RGW
  Documentation/ceph-nfs-crd.md
  build/makelib/common.mk
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  cluster/examples/kubernetes/ceph/nfs.yaml
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/csi/csi.go
  tests/framework/installer/ceph_manifests.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#163 BUG 1924792: RBD PVC creation fails with error "invalid encryption kms configuration: failed to parse kms configuration"
  cluster/charts/rook-ceph/templates/clusterrole.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  tests/framework/installer/ceph_manifests.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#164 Bug 1925004: [release-4.6] Rook changes for tuneFastDeviceClass
  Documentation/ceph-cluster-crd.md
  cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
  pkg/apis/rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/config.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#165 Bug 1922064: ceph: check for orchestration cancellation while OSDs are pending
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/status.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#166 Bug 1898808: ceph: remove crash collector if ceph pod moved
  pkg/operator/ceph/cluster/crash/reconcile.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#167 Bug 1925055: ceph: always override existing block for blkdevmapper
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#168 Bug 1922954: ceph: return an error if PVC is not clean
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/envs.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#169 Bug 1926617: better expose vault API error messages
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#170 Bug 1921864: fill up Endpoint properly for cephobjectstoreuser
  pkg/operator/ceph/object/user/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent, lgtm, ok-to-test

#171 Bug 1915005: ceph: create new osds on pvc before update existing
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_pvc_test.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/status.go
  pkg/operator/test/client.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium, lgtm

#172 Bug 1926617: ceph: do not override existing keys
  pkg/daemon/ceph/osd/kms/vault.go
  pkg/operator/ceph/cluster/osd/osd.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#174 Bug 1927023: Add tolerations for all daemons to the cleanup job
  pkg/apis/ceph.rook.io/v1/placement.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/cleanup_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#175 Bug 1896810: ceph: add ceph archive cmd in osd removal
  pkg/daemon/ceph/client/crash.go
  pkg/daemon/ceph/client/crash_test.go
  pkg/daemon/ceph/osd/remove.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#176 Bug 1928063: Enforce portable osds in same topology as osd prepare job
  Documentation/ceph-cluster-crd.md
  cmd/rook/ceph/osd.go
  cmd/rook/ceph/osd_test.go
  pkg/apis/rook.io/v1/placement.go
  pkg/apis/rook.io/v1/placement_test.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/topology.go
  pkg/operator/ceph/cluster/osd/topology_test.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/cluster/version.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/edgefs/cluster/mgr/mgr.go
  pkg/operator/edgefs/cluster/prepare/prepare.go
  pkg/operator/edgefs/cluster/target/pod.go
  pkg/operator/edgefs/iscsi/iscsi.go
  pkg/operator/edgefs/isgw/isgw.go
  pkg/operator/edgefs/nfs/nfs.go
  pkg/operator/edgefs/s3/s3.go
  pkg/operator/edgefs/s3x/s3x.go
  pkg/operator/edgefs/smb/smb.go
  pkg/operator/edgefs/swift/swift.go
  pkg/operator/k8sutil/node.go
  pkg/operator/k8sutil/node_test.go
  pkg/operator/k8sutil/pod.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#177 Bug 1931601: Consistently order the osd args to avoid restarts
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#178 Bug 1931810: ceph: fail if subfailure domains are identical
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/operator/ceph/pool/validate.go
  pkg/operator/ceph/pool/validate_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#179 Bug 1931839: ceph: show error even in silent curl
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#180 Bug 1931839: ceph: do not use curl ca-cert for signed certificates
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent
