Repository red-hat-storage/rook, pull requests merged in 2021-03, with the labels that each got.

#182 Bug 1861021: ceph: removed individual force delete pod code for mons and osds #7266
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/health.go
  pkg/operator/ceph/cluster/osd/health_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#181 Bug 1933609: unmanage labels of monitoring resources
  pkg/operator/k8sutil/prometheus.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#183 Bug 1934000: ceph: expose vault warnings better
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#186 Bug 1927922: ceph: Allow removal of arbitrary osds on pvcs and simplify pvc names
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#187 Bug 1935125: ceph: Fix improper json parsing in radosgw-admin
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/admin_test.go
  pkg/operator/ceph/object/bucket.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/operator/ceph/object/realm/controller.go
  pkg/operator/ceph/object/realm/controller_test.go
  pkg/operator/ceph/object/user.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zone/controller_test.go
  pkg/operator/ceph/object/zonegroup/controller.go
  pkg/operator/ceph/object/zonegroup/zonegroup.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#189 Bug 1937266: ceph: disable CSI GRPC metrics by default
  Documentation/helm-operator.md
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  pkg/operator/ceph/csi/csi.go
  tests/framework/installer/ceph_manifests.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#188 Bug 1937245: ceph: disable CSI GRPC metrics by default
  Documentation/helm-operator.md
  cluster/charts/rook-ceph/values.yaml
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  pkg/operator/ceph/csi/csi.go
  tests/framework/installer/ceph_manifests.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#192 Bug 1935342: ceph: add osd flapping alert
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#191 Bug 1904302: ceph: fixed prometheus query to avoid many-to-many match error
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#185 Bug 1936406: ceph: unmanage labels of monitoring resources
  pkg/operator/k8sutil/prometheus.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#195 Bug 1934990: ceph: enable pg auto repair
  pkg/operator/ceph/config/defaults.go
  pkg/operator/ceph/version/version.go
  pkg/operator/ceph/version/version_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#196 Bug 1937070: ceph: skip cleanup if cluster is not configured correctly
  pkg/operator/ceph/cluster/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#198 Bug 1939617: ceph: disable mon failover on stretched cluster
  pkg/operator/ceph/cluster/mon/health.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#199 Bug 1941647: ceph: set default backend for vault and remove temp key
  pkg/daemon/ceph/osd/kms/envs.go
  pkg/daemon/ceph/osd/kms/envs_test.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#200 Bug 1941977: ceph: fix init container "expand-encrypted-bluefs" multipath
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#201 Bug 1942515: ceph: fix init container "expand-encrypted-bluefs" multipath
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#203 Bug 1941647: ceph: remove extra slash in curl
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#204 Bug 1943275: ceph: avoid restarting all encrypted osd on cluster growth
  pkg/daemon/ceph/osd/kms/envs.go
  pkg/daemon/ceph/osd/kms/envs_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#209 Bug 1935065: ceph: prevent voluntary mon drain while another mon is failing over
  pkg/operator/ceph/cluster/mon/drain.go
  pkg/operator/ceph/cluster/mon/drain_test.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/disruption/clusterdisruption/mon.go
  pkg/operator/ceph/disruption/clusterdisruption/mon_test.go
  pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
  pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#211 Bug 1937985: ceph: enforce pg_auto_scaler on rgw pools
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/mime.go
  pkg/operator/ceph/object/objectstore.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high
