Repository red-hat-storage/rook, pull requests merged in 2021-10, with the labels that each got.

#293 Bug 2006323: [release 4.8] change ceph mgr is absent alert
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#288 Bug 2005515: Add timeout in mgr init container
  pkg/operator/ceph/cluster/mgr/spec.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high

#302 Bug 2014167: ceph: fixing the queries for alerts 'CephMgrIsAbsent' and 'CephMgrIsM…
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high

#303 Bug 1975272: ceph: fix kms auto-detection when full TLS
  pkg/daemon/ceph/osd/kms/kms.go
  pkg/daemon/ceph/osd/kms/kms_test.go
  pkg/daemon/ceph/osd/kms/vault.go
  pkg/daemon/ceph/osd/kms/vault_api.go
  pkg/daemon/ceph/osd/kms/vault_api_test.go
  pkg/daemon/ceph/osd/kms/vault_test.go
  tests/manifests/test-kms-vault-spec.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-medium

#304 Bug 1970354: ceph: handle empty ceph_version in ceph_mon_metadata
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-low

#307 Bug 1944513: [release-4.9] adding CephMonQuorumLost critical alert
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, ok-to-test, lgtm, bugzilla/severity-medium
