Repository red-hat-storage/rook, pull requests merged in 2021-07, with the labels that each got.

#272 Bug 1977379: Unset the prometheus server_addr before updating mgr
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent, lgtm

#273 bug 1974344: ceph: enable debug for adminops client if the rook loglevel <= debug
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/user/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#274 Bug 1978722: ceph: proxy ceph commands when multus is configured
  cluster/charts/rook-ceph/templates/role.yaml
  cluster/charts/rook-ceph/templates/rolebinding.yaml
  cluster/examples/kubernetes/ceph/common.yaml
  cmd/rook/rook/rook.go
  go.sum
  pkg/clusterd/context.go
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/command_test.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/orchestrator.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mgr/spec_test.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/objectstore.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_pod.go
  tests/framework/utils/k8s_helper.go
  tests/integration/ceph_base_file_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#275 Bug 1979293: ceph: always rehydrate the access and secret key
  pkg/operator/ceph/controller/object_operations.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/user/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#276 Bug 1978722: ceph: add missing spec to the object context
  pkg/operator/ceph/object/admin_test.go
  pkg/operator/ceph/object/user/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#277 Bug 1981849: ceph: add missing ceph cluster spec
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/util.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#278 Bug 1966139: [release-4.7] ceph: add osd slow ops alert
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
