Repository red-hat-storage/rook, pull requests merged in 2021-05, with the labels that each got.

#237 Bug 1959983: ceph: Persist expected mon endpoints immediately during mon failover
  pkg/operator/ceph/cluster/mon/config.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#218 Bug 1949558: ceph: add --public-addr args to ceph mds command
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mds/spec_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#239 Bug 1946573: ceph: prevent voluntary mon drain while another mon is failing over
  pkg/operator/ceph/cluster/mon/drain.go
  pkg/operator/ceph/cluster/mon/drain_test.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/disruption/clusterdisruption/mon.go
  pkg/operator/ceph/disruption/clusterdisruption/mon_test.go
  pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
  pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#238 Bug 1959980: ceph: retry once before mon failover if mon pod is unscheduled
  design/ceph/mon-health.md
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/k8sutil/pod.go
  pkg/operator/k8sutil/pod_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#224 Bug 1951348: ceph: always apply config flags for mds and rgw
  pkg/operator/ceph/file/mds/mds.go
  pkg/operator/ceph/object/rgw.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#236 Bug 1959985: ceph: Persist expected mon endpoints immediately during mon failover
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified, do-not-merge/cherry-pick-not-approved

#223 Bug 1944148: ceph: always apply config flags for mds and rgw
  pkg/operator/ceph/file/filesystem_test.go
  pkg/operator/ceph/file/mds/mds.go
  pkg/operator/ceph/object/rgw.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#243 Bug 1962109: ceph: pin volume replication to release-v0.1 branch
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  go.mod
  go.sum
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm
