Repository red-hat-storage/rook, pull requests merged in 2021-08, with the labels that each got.

#282 Bug 1994588: ceph: update CSIDriver object from betav1 to v1
  pkg/operator/ceph/csi/betav1csidriver.go
  pkg/operator/ceph/csi/csidriver.go
  pkg/operator/ceph/csi/spec.go
Labels: bugzilla/valid-bug, ok-to-test, lgtm, bugzilla/severity-high

#285 Bug 1997125: ceph: do not check ok-to-stop when OSDs are in CLBO
  pkg/daemon/ceph/client/upgrade.go
  pkg/daemon/ceph/client/upgrade_test.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#265 Bug 1989988: ceph: run CLI output with Info logging
  pkg/util/exec/exec.go
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#281 Bug 1989759: Refuse to failover the arbiter mon on stretch clusters
  pkg/operator/ceph/cluster/mon/health.go
Labels: do-not-merge/cherry-pick-not-approved

#284 Bug 1982805: Use v1 CronJob and PDB resources if available instead of v1beta1
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  go.mod
  go.sum
  pkg/operator/ceph/cluster/crash/add.go
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/crash/crash_test.go
  pkg/operator/ceph/cluster/crash/reconcile.go
  pkg/operator/ceph/cluster/mon/drain.go
  pkg/operator/ceph/cluster/mon/drain_test.go
  pkg/operator/ceph/disruption/clusterdisruption/add.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
  pkg/operator/ceph/disruption/clusterdisruption/pools.go
  pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
  pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
  pkg/operator/k8sutil/k8sutil.go
  pkg/operator/k8sutil/patcher.go
  pkg/operator/nfs/provisioner.go
  tests/framework/utils/k8s_helper.go
Labels: bugzilla/valid-bug, do-not-merge/cherry-pick-not-approved, bugzilla/severity-medium

#287 Bug 1994588: ceph: fix panic when recreating the csidriver object
  pkg/operator/ceph/csi/betav1csidriver.go
  pkg/operator/ceph/csi/csidriver.go
  pkg/operator/ceph/csi/spec.go
Labels: bugzilla/valid-bug, ok-to-test, lgtm, bugzilla/severity-high
