Repository red-hat-storage/rook, pull requests merged in 2021-09, with the labels that each got.

#20 Bug 1984396: ceph: reconcile osd pdb if allowed disruption is 0
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
Labels: bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#21 bug 2002220: ceph: retry object health check if creation fails
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/rgw.go
Labels: lgtm, bugzilla/severity-urgent, bugzilla/invalid-bug

#22 bug 2002220: rgw: fix misleading log line in rgw health checker
  .commitlintrc.json
  Documentation/development-flow.md
  pkg/operator/ceph/object/status.go
  tests/scripts/github-action-helper.sh
Labels: lgtm, bugzilla/severity-urgent, bugzilla/invalid-bug

#23 ci: backport action to build latest-4.9 iamges
  .github/workflows/odf-push-build-release-image.yaml
Labels: lgtm

#25 build: fix branch matchers for ODF release action
  .github/workflows/odf-push-build-release-image.yaml
Labels: lgtm

#27 Bug 2007130: ceph: fix external script when passing monitoring list
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/severity-medium, bugzilla/valid-bug

#26 Bug 2005290: [release 4.9] add namespace to ceph node down query
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules-external.yaml
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#29 Bug 2007377: rgw: update period if period does not exist
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
  pkg/util/exec/test/mockexec.go
Labels: bugzilla/severity-urgent, bugzilla/invalid-bug

#30 Bug 2005290: [release 4.9] Change CephAbsentMgr to use 'up' query
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#28 Bug 1983756: ceph: do not build all the args to remote exec cmd
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/command_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high
