Repository red-hat-storage/rook, pull requests merged in 2021-09, with the labels that each got.

#292 Bug 2006323: [release 4.8] add namespace to ceph node down query
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules-external.yaml
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, ok-to-test, bugzilla/severity-urgent

#290 Bug 1999605: ceph: making script backward compatible with python2
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, ok-to-test, bugzilla/severity-high

#291 Bug 1999158: option to merge placement and merge tolerations for OSDs/prepareOSD pods
  Documentation/ceph-cluster-crd.md
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
  cluster/examples/kubernetes/ceph/cluster.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  pkg/apis/rook.io/v1/placement.go
  pkg/apis/rook.io/v1/placement_test.go
  pkg/apis/rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: bugzilla/valid-bug, ok-to-test, bugzilla/severity-high

#289 Bug 1990031: Add timeout in mgr init container
  pkg/operator/ceph/cluster/mgr/spec.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high
