Repository red-hat-storage/rook, pull requests merged in 2021-06, with the labels that each got.

#246 Bug 1964467: ceph: fix external cluster upgrade
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#247 Bug 1949165: Set the location on the mon daemon for stretch clusters to reenable mon failover
  pkg/daemon/ceph/client/mon.go
  pkg/daemon/ceph/client/mon_test.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#248 Bug 1955546: ceph: stop using radosgw-admin CLI for s3 user management
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh
  cluster/examples/kubernetes/ceph/import-external-cluster.sh
  go.mod
  go.sum
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/cluster/rbd/controller.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/mirror/controller.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/bucket.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/status.go
  pkg/operator/ceph/object/user.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
  pkg/operator/ceph/pool/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#249 Bug 1925369: ceph: mons should enable v1 address type when enabling v2
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-high, needs-ok-to-test

#250 Bug 1960784: ceph: compare ceph commit hash for upgrade check
  pkg/operator/ceph/cluster/version_test.go
  pkg/operator/ceph/version/version.go
  pkg/operator/ceph/version/version_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#252 Bug 1970348: Disable insecure global id if no insecure clients
  pkg/daemon/ceph/client/config.go
  pkg/daemon/ceph/client/mgr.go
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  tests/framework/installer/ceph_installer.go
  tests/framework/installer/ceph_manifests.go
  tests/integration/ceph_upgrade_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#251 Bug 1970352: Set CSI_ENABLE_HOST_NETWORK default value to true
  pkg/operator/ceph/csi/csi.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#253 Bug 1967880: Add rbac for mgr to create service monitor
  cluster/examples/kubernetes/ceph/monitoring/rbac.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#254 Bug 1970583: Fix vault when used with kv version 2
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#256 Bug 1966139: ceph: add osd slow ops alert
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#257 Bug 1970641: ceph: use cacert if no client cert/key are present
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#258 Bug 1974399: ceph: use cacert if no client cert/key are present
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#261 Bug 1970503: sort multus annotation strings when applying
  pkg/operator/k8sutil/network.go
  pkg/operator/k8sutil/network_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#260 Bug 1974476: Disable insecure global id if no insecure clients
  pkg/daemon/ceph/client/config.go
  pkg/daemon/ceph/client/mgr.go
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent, do-not-merge/cherry-pick-not-approved

#259 Bug 1974477: Disable insecure global id if no insecure clients
  pkg/daemon/ceph/client/config.go
  pkg/daemon/ceph/client/mgr.go
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent, do-not-merge/cherry-pick-not-approved, lgtm

#262 Bug 1974443: ceph: only require rgw-admin-ops user when an endpoint is provided
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#264 Bug 1974745: ceph: do not leak key encryption key
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#263 Bug 1974748: ceph: do not leak key encryption key
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#266 Bug 1974609: ceph: initialise httpclient for bucketchecker and objectstoreuser
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/user/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high, lgtm, ok-to-test

#267 Bug 1966139: revert the slow ops alert fix
  cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent, lgtm

#268 Bug 1949165: Mons in stretch cluster must be assigned to a node
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#269 Bug 1974204: Evict a mon if colocated with another mon
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#270 Bug 1970583: ceph: cancel on-going orchestration on any CR update
  pkg/operator/ceph/cluster/predicate.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#271 Bug 1964467: ceph: do not require rgw 'instances' spec
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent
