Repository red-hat-storage/rook, pull requests merged in 2022-02, with the labels that each got.

#335 build: Add owners file for downstream integration
  OWNERS
Labels: lgtm

#340 Bug 2049718: subvolumegroup: handle external mode
  pkg/daemon/ceph/client/subvolumegroup.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#342 Bug 2048458: csi: make create and get process separate for csi users
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, ok-to-test, lgtm, bugzilla/severity-high

#343 Bug 2052937: osd: add namespace in vault client
  pkg/daemon/ceph/osd/kms/vault_api.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#344 Bug 2052996: object: do not check for upgrade on external mode
  pkg/operator/ceph/object/controller.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#345 Bug 2052996: rgw: fix variable assignment
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#346 Bug 2049075: csi: cleanup csi driver resources when zero cephclusters exist
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/predicate.go
  pkg/operator/ceph/csi/spec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#347 Bug 2055715: various external mode enhancements
  pkg/daemon/ceph/client/info.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mon/config.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#349 Bug 2028483: monitoring: making alert firing timeout and the doc timeout same
  deploy/examples/monitoring/prometheus-ceph-v14-rules.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#321 Bug 2029744: pool: file: object: clean up stop health checkers
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/pool/controller.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#352 Bug 2054898: osd: Return error if fail to list osds in prepare job
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#354 Bug 1947482: osd: Purge job will remove all pvcs for the osd
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/examples/common-second-cluster.yaml
  deploy/examples/common.yaml
  pkg/daemon/ceph/osd/remove.go
  pkg/daemon/ceph/osd/remove_test.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#353 Bug 2059027: osd: Remove osd with purge instead of destroy
  .github/workflows/canary-integration-test.yml
  pkg/daemon/ceph/osd/remove.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified
