Repository red-hat-storage/rook, pull requests merged in 2022-12, with the labels that each got.

#432 BUG 2142780: osd: re-open encrypted disk during osd-prepare-job if closed
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/config.go
  pkg/operator/ceph/cluster/osd/config_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
  pkg/util/exec/test/mockexec.go
  pkg/util/exec/translate_exec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#433 Bug 2139103: core: Set env var for ceph msgr to use random nonce
  pkg/operator/ceph/test/containers.go
  pkg/operator/k8sutil/pod.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high

#436 Bug 2144067: core: Remove unnecessary env vars from pod specs
  cmd/rook/ceph/osd.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/env.go
  pkg/operator/ceph/cluster/osd/envs.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: approved

#434 Bug 2150410: core: Set env var for ceph msgr to use random nonce
  pkg/operator/ceph/test/containers.go
  pkg/operator/k8sutil/pod.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high

#437 BUG 2142780: osd: remove stale dm device during osd-prepare-job
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/volume.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#438 Bug 2148567: osd: Allow mpath_member filesystem for mpath disks
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: approved

#435 Bug 2150411: core: Set env var for ceph msgr to use random nonce
  pkg/operator/ceph/test/containers.go
  pkg/operator/k8sutil/pod.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high

#441 Bug 2144067: core: Read mon secret from file instead of env var
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  cmd/rook/ceph/ceph.go
  cmd/rook/ceph/mgr.go
  cmd/rook/ceph/osd.go
  cmd/rook/ceph/osd_test.go
  deploy/charts/rook-ceph-cluster/templates/deployment.yaml
  deploy/examples/direct-mount.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/toolbox-job.yaml
  deploy/examples/toolbox.yaml
  design/ceph/ceph-nfs-ganesha.md
  images/ceph/toolbox.sh
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/config.go
  pkg/operator/ceph/cluster/mon/env.go
  pkg/operator/ceph/cluster/osd/envs.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
Labels: approved

#439 BUG 2153675: osd: Fix osd-prepare-job for encrypted cluster
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/config.go
  pkg/operator/ceph/cluster/osd/config_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
  pkg/util/exec/test/mockexec.go
  pkg/util/exec/translate_exec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#440 BUG 2153695: osd: Fix osd-prepare-job for encrypted cluster
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/config.go
  pkg/operator/ceph/cluster/osd/config_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
  pkg/util/exec/test/mockexec.go
  pkg/util/exec/translate_exec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#442 Bug 2152839: disable webhook
  deploy/examples/operator-openshift.yaml
  pkg/operator/ceph/controller.go
  pkg/operator/ceph/webhook-config.go
  pkg/operator/ceph/webhook.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high
