Repository red-hat-storage/rook, pull requests merged in 2022-08, with the labels that each got.

#398 Resync from Rook master to downstream release-4.12
  .github/workflows/build.yml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/crds-gen.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/linters.yaml
  .github/workflows/mod-check.yml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/stale.yaml
  .github/workflows/synk.yaml
  .github/workflows/unit-test.yml
  Documentation/Getting-Started/quickstart.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common-second-cluster.yaml
  deploy/examples/common.yaml
  deploy/examples/import-external-cluster.sh
  deploy/examples/nfs.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  design/ceph/ceph-nfs-ganesha.md
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
Labels: approved

#403 Bug 2120269: core: add support to rotate log based on logfile size
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#402 Bug 2106027: Require force flag to purge an OSD if data may be lost
  cluster/examples/kubernetes/ceph/osd-purge.yaml
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/ceph/osd/remove.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high

#401 Bug 2106026: Require force flag to purge an OSD if data may be lost
  cluster/examples/kubernetes/ceph/osd-purge.yaml
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/client/crash.go
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/ceph/osd/remove.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high

#399 Bug 2027396: Require force flag to purge an OSD if data may be lost
  cluster/examples/kubernetes/ceph/osd-purge.yaml
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/client/crash.go
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/ceph/osd/remove.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high

#395 Bug 2116416: core: add support to rotate log based on logfile size
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#400 Bug 2106025: Require force flag to purge an OSD if data may be lost
  cluster/examples/kubernetes/ceph/osd-purge.yaml
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/client/crash.go
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/ceph/osd/remove.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high

#405 Bug 2120598: mon: Improve mon failover reliability [4.11]
  .github/workflows/codespell.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster.yaml
  deploy/examples/operator-openshift.yaml
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  tests/framework/utils/exec_utils.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high

#406 Bug 2120601: mon: Improve mon failover reliability [4.10]
  .github/workflows/codespell.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster.yaml
  deploy/examples/operator-openshift.yaml
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  tests/framework/utils/exec_utils.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high
