Repository red-hat-storage/rook, pull requests merged in 2022-04, with the labels that each got.

#363 Bug 2069795: core: reload go routine after CR is edited
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/monitoring.go
  pkg/operator/ceph/cluster/osd/health.go
  pkg/operator/ceph/cluster/osd/health_test.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/health.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#365 Bug 2074558: osd: only set kek to env var on encryption scenario
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/kms/envs.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#372 Resync from upstream release-1.9 to downstream 4.11
  Documentation/ceph-monitoring.md
  Documentation/ceph-upgrade.md
  Documentation/quickstart.md
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/examples/common.yaml
  deploy/examples/direct-mount.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/toolbox-job.yaml
  deploy/examples/toolbox.yaml
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  tests/framework/installer/ceph_manifests.go
  tests/integration/ceph_smoke_test.go
Labels: approved

#373 BUG 2078713: csi: add/remove mon IP from csi config
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#364 Bug 2069722: ceph: add ceph cluster fsid to LUKS header
  pkg/apis/ceph.rook.io/v1/security.go
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/command_test.go
  pkg/daemon/ceph/client/info.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/encryption_test.go
  pkg/daemon/ceph/osd/kms/envs.go
  pkg/daemon/ceph/osd/kms/vault.go
  pkg/daemon/ceph/osd/kms/volumes.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mgr/spec_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/object/admin.go
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
  tests/scripts/validate_cluster.sh
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high

#351 Bug 2052608: csi: make create and get process separate for csi users [4.8]
  .github/workflows/canary-integration-test.yml
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: approved, lgtm, bugzilla/severity-high

#350 Bug 2052607: csi: make create and get process separate for csi users [4.9]
  .github/workflows/canary-integration-test.yml
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high
