Repository red-hat-storage/rook, pull requests merged in 2022-01, with the labels that each got.

#328 Bug 2041964: osd: correct bluestore compression min blob size for ssd
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#317 Bug 2030291: ceph: add ceph cluster fsid to LUKS header
  pkg/apis/ceph.rook.io/v1/security.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/encryption_test.go
  pkg/daemon/ceph/osd/kms/envs.go
  pkg/daemon/ceph/osd/kms/vault.go
  pkg/daemon/ceph/osd/kms/volumes.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
Labels: bugzilla/invalid-bug, bugzilla/severity-medium

#331 Bug 2043186: osd: correct bluestore compression min blob size for ssd
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#332 Bug 2043185: ceph: correct bluestore compression min blob size for ssd
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#333 Bug 2043179: osd: correct bluestore compression min blob size for ssd
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent
