Repository red-hat-storage/rook, pull requests merged in 2022-11, with the labels that each got.

#426 BUG 2135849: do not create service for external object stores
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/notification/controller_test.go
  pkg/operator/ceph/object/notification/obc_label_controller_test.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  pkg/operator/ceph/object/status.go
  tests/framework/utils/k8s_helper.go
  tests/integration/ceph_object_test.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-urgent

#427 Bug 2141947: object: mark endpoint as a optional field
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#430 bug 2135849: object: update to latest obc controller to fix ob status
  go.mod
  go.sum
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#429 BUG 2142902: csi: disable liveness sidecar by default
  Documentation/helm-operator.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#428 BUG 2142901: csi: disable liveness sidecar by default
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#431 Bug 2143899: core: Parse peer pool ouput with --out-file flag
  pkg/operator/ceph/csi/peermap/config.go
  pkg/operator/ceph/csi/peermap/config_test.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-urgent
