Repository red-hat-storage/rook, pull requests merged in 2022-10, with the labels that each got.

#419 Bug 2130497: osd: use 256 as cryptographicLength for keys using kmip kms
  pkg/daemon/ceph/osd/kms/kmip.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium

#420 Bug 2133550: fix NFS when multus is enabled
  .github/workflows/canary-integration-test.yml
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/command_test.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
  tests/scripts/github-action-helper.sh
Labels: bugzilla/valid-bug, approved, bugzilla/severity-unspecified

#421 Bug 2130279: ceph: fixing ClientID of log-collector for RGW instance
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#422 Bug 2126566: Increase liveness probe timeout to 5s
  pkg/operator/ceph/controller/spec.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-urgent

#423 BUG 2135830: csi: add setmetadata and clustername flag to omap
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: bugzilla/valid-bug, bugzilla/severity-medium

#424 Bug 2134769: external: fix endpoint_dial check for rgw endpoint
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, bugzilla/severity-unspecified

#425 Bug 2128966: osd: osdSafeToDestroy check should be after osd out
  pkg/daemon/ceph/osd/remove.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high
