Repository red-hat-storage/rook, pull requests merged in 2022-09, with the labels that each got.

#409 Resync from upstream release-1.10 to downstream 4.12
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  build/crds/build-crds.sh
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
  deploy/examples/crds.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/predicate.go
  pkg/operator/ceph/csi/predicate_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  tests/framework/installer/ceph_installer.go
  tests/scripts/github-action-helper.sh
Labels: approved

#410 Resync from upstream 1.10 to downstream 4.12
  Documentation/Getting-Started/quickstart.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Advanced/key-management-system.md
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
  Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
  Documentation/Upgrade/rook-upgrade.md
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/csi/nfs/pvc-clone.yaml
  deploy/examples/csi/nfs/pvc-restore.yaml
  deploy/examples/csi/nfs/rbac.yaml
  deploy/examples/csi/nfs/snapshot.yaml
  deploy/examples/csi/nfs/snapshotclass.yaml
  deploy/examples/csi/nfs/storageclass.yaml
  deploy/examples/direct-mount.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/toolbox-job.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/security.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/kms/envs.go
  pkg/daemon/ceph/osd/kms/envs_test.go
  pkg/daemon/ceph/osd/kms/k8s.go
  pkg/daemon/ceph/osd/kms/kmip.go
  pkg/daemon/ceph/osd/kms/kmip_test.go
  pkg/daemon/ceph/osd/kms/kms.go
  pkg/daemon/ceph/osd/kms/kms_test.go
  pkg/daemon/ceph/osd/kms/volumes.go
  pkg/daemon/ceph/osd/kms/volumes_test.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
Labels: approved

#413 Resync from upstream release-1.10 to downstream 4.12 branch
  Documentation/CRDs/Object-Storage/ceph-object-multisite-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Helm-Charts/operator-chart.md
  build/rbac/get-helm-rbac.sh
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/object-multisite-test.yaml
  deploy/examples/object-multisite.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  design/ceph/object/ceph-multisite-overview.md
  design/ceph/object/zone.md
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/dependents.go
  pkg/operator/ceph/object/dependents_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zone/dependents.go
  pkg/operator/ceph/object/zone/dependents_test.go
  pkg/operator/ceph/pool/controller.go
Labels: approved

#414 Sync from upstream release-1.10 to downstream 4.12
  .github/workflows/daily-nightly-jobs.yml
  Documentation/CRDs/Cluster/external-cluster.md
  Documentation/CRDs/ceph-nfs-crd.md
  Documentation/Storage-Configuration/NFS/nfs-security.md
  Documentation/Storage-Configuration/NFS/nfs.md
  build/rbac/keep-rbac-yaml.sh
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/monitoring/localrules.yaml
  deploy/examples/nfs.yaml
  design/ceph/ceph-nfs-ganesha.md
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/nfs.go
  pkg/apis/ceph.rook.io/v1/nfs_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/rados.go
  pkg/daemon/ceph/client/rados_test.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
  pkg/operator/ceph/nfs/security.go
  pkg/operator/ceph/nfs/security_test.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/nfs/spec_test.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
  pkg/util/exec/test/mockexec.go
Labels: approved

#411 BUG 2122215: csi: remove findCSIChange from predicate
  pkg/operator/ceph/csi/predicate.go
  pkg/operator/ceph/csi/predicate_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#415 BUG 2123626: fix holder pod creation in openshift multus cluster
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#412 BUG 2125148: csi: remove findCSIChange from predicate
  pkg/operator/ceph/csi/predicate.go
  pkg/operator/ceph/csi/predicate_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#416 Bug 2130110: external: do not add info=read cap if ceph version doesn't support it
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, bugzilla/severity-medium
