Repository red-hat-storage/rook, pull requests merged in 2022-03, with the labels that each got.

#356 BUG 2062559: core: fix empty string bug
  pkg/operator/ceph/csi/util.go
  pkg/operator/ceph/csi/util_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#357 Bug 2061657: osd: clarify vault auth error message
  pkg/daemon/ceph/osd/kms/vault_api.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#358 Bug 2061675: core: rework usage of ReportReconcileResult
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/notification/obc_label_controller.go
  pkg/operator/ceph/reporting/reporting.go
  pkg/operator/ceph/reporting/reporting_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#360 Bug 1996833: core: fix incorrect join command
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm

#361 Bug 2063301: mon: Disable startup probe on canary pods
  pkg/operator/ceph/cluster/mon/mon.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high
