Repository red-hat-storage/rook, pull requests merged in 2022-06, with the labels that each got.

#382 Bug 2092143: Delete ceph pool when blockpool cr is deleted and fix canary tests
  .github/workflows/setup-cluster-resources/action.yaml
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/pool_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/validate.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-unspecified

#383 Bug 2089755: osd: do not hide the error
  pkg/daemon/ceph/osd/kms/kms_test.go
  pkg/daemon/ceph/osd/kms/vault.go
  pkg/operator/ceph/object/spec_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#384 Bug 2089137: external-script: remove signature import
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#385 Bug 2088506: rgw: make fqdn rgw converted to ip everywhere
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#387 Bug 2095155: core: format python files using tool black
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#386 Bug 2069314: csi: make storage class updated with csi-users in external cluster
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/ceph-cluster-crd.md
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#391 Bug 2098536: csi: add token create rbac for rbd csi clusterrole
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#389 Bug 2097740: osd: add lvm flag for lvm osd activate
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#393 Bug 2098621: core: delete v1beta1 cronjob only when v1 not found
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/crash/reconcile.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-unspecified

#394 Bug 2100946: mon: Disable insecure global ids for new deployments
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/config/config.go
  pkg/operator/ceph/config/config_test.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-unspecified
