Repository red-hat-storage/rook, pull requests merged in 2023-09, with the labels that each got.

#516 Bug 2236444: monitoring: set port for servicemonitor for ceph-exporter
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
  pkg/operator/k8sutil/prometheus.go
  pkg/operator/k8sutil/prometheus_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#511 Bug 2233674: core: operator skips reconcile of mons and osds in debug
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
Labels: approved

#518 Bug 2228785: object: avoid creating same bucket for two different OBC
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
Labels: bugzilla/invalid-bug, lgtm, bugzilla/severity-low

#520 bug 2218952: multus: detect network CIDRs via canary
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Advanced/ceph-configuration.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  pkg/apis/ceph.rook.io/v1/cluster.go
  pkg/apis/ceph.rook.io/v1/network.go
  pkg/apis/ceph.rook.io/v1/network_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/cluster/mon/node_test.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/config/config.go
  pkg/operator/ceph/config/monstore.go
  pkg/operator/ceph/config/network.go
  pkg/operator/ceph/config/network_test.go
  pkg/operator/ceph/controller/cluster_info_test.go
  pkg/operator/ceph/controller/network.go
  pkg/operator/ceph/controller/network_test.go
  pkg/operator/ceph/csi/controller_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
  pkg/operator/k8sutil/network.go
  pkg/operator/k8sutil/network_test.go
Labels: bugzilla/valid-bug, bugzilla/severity-unspecified

#521 Bug 2223959: osd: make osd pod to sleep when osds are flapping
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high

#519 Bug 2237861: Disable exporter 4.13
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
  pkg/operator/k8sutil/prometheus.go
Labels: approved, bugzilla/invalid-bug, lgtm, bugzilla/severity-unspecified

#523 Bug 2239802: external: update healthchecker caps for rbd command
  .github/workflows/canary-integration-test.yml
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
  tests/scripts/github-action-helper.sh
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#497 Bug 2189727: external: fqdn should be persisted
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/object-external.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: approved, lgtm

#503 Bug 2229646: external: fqdn should be persisted
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/object-external.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium
