Repository red-hat-storage/rook, pull requests merged in 2023-05, with the labels that each got.

#486 Bug 2190523: test: add multus validation test routine to rook binary
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  cmd/rook/ceph/ceph.go
  cmd/rook/discover.go
  cmd/rook/main.go
  cmd/rook/rook/rook.go
  cmd/rook/secret.go
  cmd/rook/userfacing/multus/multus.go
  cmd/rook/userfacing/multus/validation/validation.go
  cmd/rook/userfacing/userfacing.go
  cmd/rook/util/cmdreporter.go
  cmd/rook/util/copybins.go
  design/common/multi-homed-cluster.md
  design/common/multi-net-multus.md
  go.mod
  go.sum
  pkg/daemon/multus/client-daemonset.yaml
  pkg/daemon/multus/nginx-config.yaml
  pkg/daemon/multus/nginx-pod.yaml
  pkg/daemon/multus/resources.go
  pkg/daemon/multus/statemachine.go
  pkg/daemon/multus/templates.go
  pkg/daemon/multus/util.go
  pkg/daemon/multus/validation.go
Labels: approved, lgtm

#488 BUG 2192088: unset all the encryption configuration before setting
  pkg/operator/ceph/config/monstore.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#483 Bug 2192824: external: fixed validate_rgw_endpoint pool validation
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#485 Bug 2192823: rgw: fixed validate_rgw_endpoint pool validation
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#489 Bug 2192821: external: fix rgw check if no multisite flag is passed
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#491 Bug 2192823: external: fix rgw check if no multisite flag is passed
  deploy/examples/create-external-cluster-resources.py
Labels: approved, bugzilla/invalid-bug, lgtm, bugzilla/severity-urgent

#490 Bug 2192824: external: fix rgw check if no multisite flag is passed
  deploy/examples/create-external-cluster-resources.py
Labels: approved, bugzilla/invalid-bug, lgtm, bugzilla/severity-urgent

#492 Bug 2208079: rbdmirror: Retry reconcile if cluster not initialized
  pkg/operator/ceph/cluster/rbd/controller.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-unspecified

#494 Bug 2209643: object: use networkspec from clusterinfo spec while running radosgw-admin
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/admin_test.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/provisioner.go
  pkg/operator/ceph/object/topic/provisioner.go
  pkg/operator/ceph/object/user/controller.go
Labels: approved
