Repository red-hat-storage/rook, pull requests merged in 2023-08, with the labels that each got.

#504 Bug 2221488: monitoring: enable exporter for downstream 4.14
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high

#510 bug 2233010: replace osd to use new backend store
  Documentation/CRDs/specification.md
  cmd/rook/ceph/osd.go
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/cleanup/disk.go
  pkg/daemon/ceph/osd/agent.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/device.go
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/envs.go
  pkg/operator/ceph/cluster/osd/health.go
  pkg/operator/ceph/cluster/osd/health_test.go
  pkg/operator/ceph/cluster/osd/labels.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/replace.go
  pkg/operator/ceph/cluster/osd/replace_test.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/k8sutil/configmap.go
  pkg/operator/k8sutil/configmap_test.go
Labels: bugzilla/invalid-bug, lgtm, bugzilla/severity-high

#498 BUG 2222600: csi: update csi holder daemonset template
  pkg/operator/ceph/csi/spec.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#502 Bug 2227161: core: force delete rook-ceph-exporter pod
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#513 Bug 2224307: build: update go modules
  .github/workflows/build_dependabot_bundler_pr.yml
  .github/workflows/update_dependabot_bundler_pr.yml
  build/makelib/golang.mk
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#515 Bug 2235395: core: return valid CIDR ip
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#512 Bug 2233615: core: Operator skips reconcile of mons and osds in debug
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
Labels: approved
