Repository red-hat-storage/rook, pull requests merged in 2023-03, with the labels that each got.

#453 core: remove ceph version check for mcs api
  pkg/operator/ceph/cluster/cluster.go
Labels: lgtm

#458 Final resync from upstream release-1.11 to downstream release-4.13 branch
  Documentation/Getting-Started/quickstart.md
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
  Documentation/Upgrade/rook-upgrade.md
  build/csv/csv-gen.sh
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/direct-mount.yaml
  deploy/examples/images.txt
  deploy/examples/import-external-cluster.sh
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/toolbox-job.yaml
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/topology/topology.go
  pkg/operator/ceph/cluster/osd/topology/topology_test.go
  pkg/operator/ceph/config/monstore.go
  pkg/operator/ceph/object/rgw.go
Labels: approved

#446 Bug 2089137: rgw: dont do rgw validation if python version < 3
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#462 ci: stop running ci concurrently when pr is fresh
  .github/workflows/canary-integration-test.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
Labels: approved, lgtm

#463 ci: stop running ci concurrently when pr is fresh
  .github/workflows/canary-integration-test.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
Labels: approved, lgtm

#465 ci: ubuntu 18.04 is deprecated upgrade to ubuntu 22.04
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yml
  .github/workflows/crds-gen.yml
  .github/workflows/create-tag.yaml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/mod-check.yml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/stale.yaml
  .github/workflows/unit-test.yml
  pkg/daemon/ceph/client/config.go
  pkg/daemon/ceph/osd/kms/vault.go
  pkg/daemon/ceph/util/util.go
  pkg/operator/ceph/cluster/osd/envs_test.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/discover/discover.go
  pkg/operator/test/client.go
  pkg/util/file.go
  tests/scripts/create-bluestore-partitions.sh
Labels: approved, lgtm

#455 [release-4.10] Bug 2171963: core: Remove unnecessary env vars from pod specs
  cmd/rook/ceph/ceph.go
  cmd/rook/ceph/mgr.go
  cmd/rook/ceph/osd.go
  cmd/rook/ceph/osd_test.go
  deploy/charts/rook-ceph-cluster/templates/deployment.yaml
  deploy/examples/direct-mount.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/toolbox-job.yaml
  deploy/examples/toolbox.yaml
  images/ceph/toolbox.sh
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/config.go
  pkg/operator/ceph/cluster/mon/env.go
  pkg/operator/ceph/cluster/osd/envs.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-high
