Repository red-hat-storage/rook, pull requests merged in 2023-11, with the labels that each got.

#534 Syncing latest changes from master for rook
  .github/workflows/helm-lint.yaml
  Documentation/Contributing/development-environment.md
  Documentation/Troubleshooting/disaster-recovery.md
  deploy/examples/cluster-on-pvc-minikube.yaml
  go.mod
  go.sum
  images/ceph/Makefile
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/object/admin_test.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/dependents_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/zone/controller_test.go
  pkg/operator/ceph/object/zonegroup/controller_test.go
  tests/scripts/create-dev-cluster.sh
Labels: lgtm

#533 Bug 2245978: multus: use rook image for ip range detection
  .github/workflows/helm-lint.yaml
  build/csv/csv-gen.sh
  build/release/requirements_docs.txt
  mkdocs.yml
  pkg/operator/ceph/controller/network.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#537 Bug 2249735: fix multus net detect job all placement
  .github/workflows/canary-integration-test.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/encryption-pvc-kms-ibm-kp/action.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/rgw-multisite-test/action.yml
  pkg/operator/ceph/controller/network.go
  pkg/operator/ceph/controller/network_test.go
  tests/framework/utils/k8s_helper.go
  tests/integration/ceph_base_object_test.go
  tests/scripts/github-action-helper.sh
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#541 Bug 2248850: exporter: run exporter with specific keyring
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/keyring.go
  pkg/operator/ceph/cluster/nodedaemon/keyring_test.go
  pkg/operator/ceph/config/keyring/admin.go
  pkg/operator/ceph/config/keyring/volume.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#542 Bug 2248850: exporter: change deployment strategy to Recreate
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
Labels: bugzilla/valid-bug, bugzilla/severity-high
