Repository red-hat-storage/rook, pull requests merged in 2023-04, with the labels that each got.

#468 Bug 2139451: external: make rgw call separate from cephfs and rbd
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#469 nfs: add support for nfs-ganesha metrics monitoring
  pkg/operator/ceph/nfs/spec.go
Labels: approved, lgtm

#447 Bug 2167304: security: run the crash collector as ceph user
  .docs/macros/includes/main.py
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/crash/crash_test.go
  pkg/operator/ceph/controller/spec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#459 Bug 2180728: security: run the crash collector as ceph user
  .docs/macros/includes/main.py
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/crash/crash_test.go
  pkg/operator/ceph/controller/spec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#460 Bug 2180732: security: run the crash collector as ceph user
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/crash/crash_test.go
  pkg/operator/ceph/controller/spec.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#470 Bug 2183457: Use clusterID for nslookup of exported IPs
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/mon/service.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/k8sutil/service.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#471 Bug 2177106: external: add alias rbd pool name to support . pools name
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
Labels: approved, lgtm

#472 Bug 2167516: external: add support for multisite in external cluster script
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
Labels: approved, bugzilla/invalid-bug, lgtm, bugzilla/severity-medium

#475 external: add alias rbd pool name to support . pools name
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
Labels: approved, lgtm

#479 Bug 2188379: Backport 4.12 multisite support
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#481 Bug 2187765: [4.12 backport] skip OBC and Notification controllers
  pkg/operator/ceph/object/bucket/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/controller.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#478 Bug 2177106: external: check for pool and cluster name is provided
  deploy/examples/create-external-cluster-resources.py
Labels: approved, lgtm

#482 Bug: 2183266: core: skip OBC and Notification controllers
  pkg/operator/ceph/object/bucket/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/controller.go
Labels: approved, lgtm

#474 Bug 2187952: Disable exporter service for downstream 4.13
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#477 Bug 2188381: external: add alias rbd pool name to support . pools name
  deploy/examples/create-external-cluster-resources.py
Labels: approved, lgtm
