Repository red-hat-storage/rook, pull requests merged in 2023-10, with the labels that each got.

#525 Bug 2234377: mds: improve the mds liveness probe calls
  .github/workflows/unit-test.yml
  pkg/operator/ceph/file/mds/livenessprobe.go
  pkg/operator/ceph/file/mds/livenessprobe.sh
  pkg/operator/ceph/file/mds/livenessprobe_test.go
  pkg/operator/ceph/file/mds/mds.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mds/spec_test.go
  pkg/operator/ceph/file/mds/test/0FS-2MDS.json
  pkg/operator/ceph/file/mds/test/0FS.json
  pkg/operator/ceph/file/mds/test/1FS-2MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(0,0)MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(0,2)MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(1,2)MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(2,2)MDS.json
Labels: lgtm

#528 Bug 2242433: osd: use bash script if restart interval is > 0
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: lgtm

#529 Syncing latest changes from master for rook
  Documentation/Storage-Configuration/Object-Storage-RGW/cosi.md
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/scc.go
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
Labels: lgtm

#526 BUG 2242374: build: update go module deps
  go.mod
  go.sum
Labels: bugzilla/invalid-bug, lgtm, bugzilla/severity-urgent

#532 Bug 2239802: pool: rbd cmd shouldn't use admin in external mode
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#531 Syncing latest changes from master for rook
  .github/workflows/commitlint.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .snyk
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Contributing/ci-configuration.md
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Storage-Configuration/Advanced/ceph-configuration.md
  Documentation/Storage-Configuration/Monitoring/ceph-dashboard.md
  Documentation/Troubleshooting/kubectl-plugin.md
  Documentation/Upgrade/ceph-upgrade.md
  README.md
  build/csv/csv-gen.sh
  build/release/requirements_docs.txt
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/common-second-cluster.yaml
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/dashboard-external-http.yaml
  deploy/examples/dashboard-external-https.yaml
  deploy/examples/dashboard-loadbalancer.yaml
  deploy/examples/monitoring/exporter-service-monitor.yaml
  deploy/examples/monitoring/service-monitor.yaml
  deploy/examples/nfs-load-balancer.yaml
  deploy/examples/osd-env-override.yaml
  deploy/examples/pool-mirrored.yaml
  deploy/examples/sqlitevfs-client.yaml
  deploy/examples/volume-replication-class.yaml
  go.mod
  go.sum
  mkdocs.yml
  pkg/operator/ceph/cluster/nodedaemon/keyring.go
  pkg/operator/ceph/cluster/nodedaemon/keyring_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/user/controller_test.go
  pkg/operator/k8sutil/node.go
Labels: lgtm
