Repository red-hat-storage/rook, pull requests merged in 2024-05, with the labels that each got.

#640 Bug 2262134: mon: Disable v1 port if msgr2 is required
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/mon/spec_test.go
Labels: bugzilla/valid-bug, bugzilla/severity-medium

#631 Bug 2276532: osd: Legacy osds on lvm pvcs crash on resize init container
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-urgent

#643 BUG 2278606: csi: fix missing namespace bug in csi cluster config map
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#644 Syncing latest changes from upstream master for rook
  cmd/rook/ceph/mgr.go
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/mgr/mgr.go
Labels: lgtm

#646 Bug 2269099: osd: limit storageClassDeviceSets to 63 chars
  .github/workflows/golangci-lint.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-low

#647 Bug 2279992: csi: add a new flag to disable csi driver
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/controller.go
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#648 Bug 2274757: osd: Add cephcluster status for legacy osds to replace
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#645 Syncing latest changes from upstream master for rook
  .docs/macros/includes/main.py
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yml
  .github/workflows/crds-gen.yml
  .github/workflows/create-tag.yaml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/mod-check.yml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/stale.yaml
  .github/workflows/unit-test.yml
  Documentation/CRDs/Block-Storage/ceph-block-pool-rados-namespace-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-clone.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/release/Makefile
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/filesystem_mirror.go
  pkg/daemon/ceph/client/filesystem_mirror_test.go
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/cluster/nodedaemon/crash_test.go
  pkg/operator/ceph/cluster/nodedaemon/pruner_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/mirror/config.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/version/version_test.go
Labels: lgtm

#650 csv: Update csv version
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
Labels: lgtm

#652 Bug 2280946: core: remove owner refs in resource cleanup jobs
  pkg/operator/ceph/controller/cleanup.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#653 Bug 2281580: core: fix missing env in svg cleanup job
  pkg/operator/ceph/file/subvolumegroup/controller.go
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#654 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Block-Storage/ceph-block-pool-rados-namespace-crd.md
  pkg/operator/ceph/controller/cleanup.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
Labels: lgtm

#655 Syncing latest changes from upstream master for rook
  deploy/charts/rook-ceph-cluster/values.yaml
  pkg/operator/ceph/cluster/predicate.go
  pkg/operator/ceph/cluster/predicate_test.go
Labels: lgtm

#656 BUG 2282254: mon: fix bind addr when IPv6 and msgr2 are enabled
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/mon/spec_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#657 Syncing latest changes from upstream master for rook
  .github/workflows/codespell.yaml
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/mon/spec_test.go
  pkg/operator/ceph/pool/controller_test.go
Labels: lgtm

#660 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/client/informers/externalversions/factory.go
  pkg/daemon/ceph/osd/remove.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/replace.go
  pkg/operator/ceph/cluster/osd/replace_test.go
  pkg/operator/ceph/cluster/osd/update.go
Labels: lgtm

#661 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/osd.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  tests/framework/installer/ceph_manifests.go
Labels: lgtm
