Repository red-hat-storage/rook, pull requests merged in 2024-06, with the labels that each got.

#664 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/network-providers.md
  ROADMAP.md
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/makelib/golang.mk
  deploy/examples/create-external-cluster-resources.py
  go.mod
  go.sum
  pkg/daemon/multus/nginx-config.yaml
  pkg/daemon/multus/templates.go
  pkg/operator/ceph/cluster/mon/node.go
  pkg/operator/ceph/cluster/mon/node_test.go
  tests/scripts/multus/default-public-cluster-nads.yaml
Labels: lgtm

#665 Syncing latest changes from upstream master for rook
  deploy/examples/monitoring/exporter-service-monitor.yaml
Labels: lgtm

#666 Syncing latest changes from master for rook
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/network-providers.md
  Documentation/CRDs/specification.md
  ROADMAP.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/makelib/golang.mk
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/monitoring/exporter-service-monitor.yaml
  go.mod
  go.sum
  images/ceph/Dockerfile
  pkg/apis/ceph.rook.io/v1/network.go
  pkg/apis/ceph.rook.io/v1/network_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/multus/nginx-config.yaml
  pkg/daemon/multus/templates.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/cluster/mon/node.go
  pkg/operator/ceph/cluster/mon/node_test.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
  tests/framework/installer/ceph_manifests.go
  tests/scripts/multus/default-public-cluster-nads.yaml
Labels: lgtm

#667 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystems.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
  deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/monitoring/localrules.yaml
  deploy/examples/monitoring/service-monitor.yaml
  deploy/examples/pool.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/operator/k8sutil/prometheus.go
Labels: lgtm

#668 Syncing latest changes from master for rook
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystems.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
  deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/monitoring/localrules.yaml
  deploy/examples/monitoring/service-monitor.yaml
  deploy/examples/pool.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/operator/k8sutil/prometheus.go
Labels: lgtm

#670 Syncing latest changes from upstream master for rook
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: lgtm

#669 Bug 2293881: osd: revert limit storageClassDeviceSets to 63 chars
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  images/ceph/Dockerfile
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#671 BUG 2293621: osd: use old passphrase to kill the luks slot
  pkg/daemon/ceph/osd/encryption.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#672 Syncing latest changes from upstream master for rook
  go.mod
  go.sum
  pkg/daemon/ceph/osd/encryption.go
Labels: lgtm
