Repository red-hat-storage/rook, pull requests merged in 2024-12, with the labels that each got.

#785 Syncing latest changes from upstream master for rook
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
  pkg/apis/ceph.rook.io/v1/annotations.go
  pkg/apis/ceph.rook.io/v1/annotations_test.go
Labels: approved, lgtm

#781 DFBUGS-901: ci: fix ci issue downstream
  .github/workflows/codespell.yaml
  design/ceph/osd-migration.md
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/pool/controller_test.go
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-low

#795 DFBUGS-979: csi: disable fencing in Rook
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#796 DFBUGS-980: csi: disable fencing in Rook
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#797 DFBUGS-979: Revert "csi: disable fencing in Rook"
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, jira/valid-reference, jira/valid-bug

#798 DFBUGS-980: Revert "csi: disable fencing in Rook"
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug
