Repository red-hat-storage/rook, pull requests merged in 2024-09, with the labels that each got.

#714 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/templates/securityContextConstraints.yaml
  deploy/examples/crds.yaml
  deploy/examples/object.yaml
  deploy/examples/operator-openshift.yaml
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/apis/ceph.rook.io/v1/labels_test.go
  pkg/apis/ceph.rook.io/v1/nfs_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/volume.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/nfs/security.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  pkg/operator/k8sutil/k8sutil.go
  pkg/operator/k8sutil/k8sutil_test.go
Labels: lgtm

#715 Bug 2294118: build: update go-retryablehttp from 0.7.5 to 0.7.7
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#716 Bug 2295778: osd: allow the AllowOsdCrushWeightUpdate flag always true
  pkg/operator/ceph/cluster/osd/osd.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high

#718 Fix csv-gen script to correctly replace ROOK_IMAGE env var
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/csv/csv-gen.sh
  deploy/olm/assemble/metadata-common.yaml
Labels: lgtm

#719 Bug 2308446:[release-4.17] Fix csv-gen script to correctly replace ROOK_IMAGE env var
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/csv/csv-gen.sh
  deploy/olm/assemble/metadata-common.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#711 Bug 2297285: exporter: bind to all interfaces if IPv6 is enabled
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#722 Manual sync of u/s master with d/s master
  .github/workflows/docs-check.yml
  Documentation/Contributing/documentation.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  Makefile
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
  tests/scripts/validate_modified_files.sh
Labels: lgtm

#530 Bug 2268174: external: change cluster_name to k8s_cluster_name
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#720 Bug 2292435: mon: Remove extra mon from quorum before taking down pod
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-unspecified

#556 Bug 2254345: [release-4.14] external - fix the run as a user flag
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#725 Bug 2308304: csi: stop deleting csi-operator resources
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/operator_config.go
  pkg/operator/ceph/csi/spec.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high

#726 Syncing latest changes from upstream master for rook
  .github/workflows/commitlint.yml
  .github/workflows/docs-check.yml
  .github/workflows/snyk.yaml
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  Makefile
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/crush.go
  pkg/daemon/ceph/client/crush_rule.go
  pkg/daemon/ceph/client/crush_rule_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/operator_config.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/json_helpers.go
  pkg/operator/ceph/object/json_helpers_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/operator/ceph/object/shared_pools.go
  pkg/operator/ceph/object/shared_pools_test.go
  pkg/operator/ceph/object/zone/controller.go
Labels: lgtm

#730 Bug 2297454: core: check for duplicate ceph fs pool names
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#731 Syncing latest changes from upstream master for rook
  .github/workflows/codespell.yaml
  .github/workflows/docs-check.yml
  .github/workflows/scorecards.yml
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
  deploy/examples/monitoring/grafana/Ceph Cluster Dashboard.json
  deploy/examples/monitoring/grafana/Ceph OSD Single Dashboard.json
  deploy/examples/monitoring/grafana/Ceph Pools Dashboard.json
  deploy/examples/monitoring/grafana/README.md
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm

#729 external: add a new configmap to store external cluster script
  build/csv/ceph/rook-ceph-external-cluster-script-config_v1_configmap.yaml
  build/csv/csv-gen.sh
  deploy/examples/external-cluster-script-configmap.yaml
  deploy/examples/kustomization.yaml
Labels: lgtm

#733 Bug 2310385: external: mds caps to healthchecker/cephfs users
  .github/workflows/canary-test-config/action.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/create-external-cluster-resources.py
  tests/scripts/github-action-helper.sh
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#734 Bug 2313736: csi: fix the disable driver flag in the csi driver reconcile
  pkg/operator/ceph/csi/controller.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high
