Repository red-hat-storage/rook, pull requests merged in 2024-04, with the labels that each got.

#612 Syncing latest changes from upstream master for rook
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/commitlint.yml
  .mergify.yml
  Documentation/CRDs/Cluster/external-cluster/topology-for-external-mode.md
  Makefile
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephbucketnotifications.yaml
  build/csv/ceph/ceph.rook.io_cephbuckettopics.yaml
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/csv/ceph/ceph.rook.io_cephcosidrivers.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemmirrors.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystems.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  build/csv/ceph/ceph.rook.io_cephnfses.yaml
  build/csv/ceph/ceph.rook.io_cephobjectrealms.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstoreusers.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzonegroups.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  build/csv/ceph/ceph.rook.io_cephrbdmirrors.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/makelib/golang.mk
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
  go.mod
  go.sum
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
Labels: lgtm

#613 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/network-providers.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephbuckettopics.yaml
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemmirrors.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstoreusers.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzonegroups.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  build/csv/ceph/ceph.rook.io_cephrbdmirrors.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/crds.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/status.go
  pkg/operator/ceph/pool/status_test.go
Labels: lgtm

#594 ci: push downstream image to ocs/dev
  .github/workflows/push-build-downstream.yaml
  tests/scripts/build-release-downstream.sh
Labels: lgtm

#614 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: lgtm

#577 Bug 2264553: mon: set mon pdb max unavailable as 2 in case of 5 or more mons
  pkg/operator/ceph/cluster/mon/drain.go
  pkg/operator/ceph/cluster/mon/drain_test.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#619 Bug 2269205: build: update go dep go-jose
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#621 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/ceph-teardown.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  cmd/rook/ceph/cleanup.go
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  deploy/examples/subvolumegroup.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/cleanup/subvolumegroups.go
  pkg/daemon/ceph/cleanup/subvolumegroups_test.go
  pkg/daemon/ceph/client/filesystem.go
  pkg/daemon/ceph/client/filesystem_test.go
  pkg/daemon/ceph/client/subvolumegroup.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
  pkg/operator/ceph/controller/cleanup.go
  pkg/operator/ceph/controller/cleanup_test.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
  pkg/operator/ceph/file/mds/mds.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  tests/framework/installer/ceph_manifests.go
Labels: lgtm

#624 Syncing latest changes from upstream master for rook
  Documentation/Storage-Configuration/ceph-teardown.md
  cmd/rook/ceph/cleanup.go
  pkg/daemon/ceph/cleanup/radosnamespace.go
  pkg/daemon/ceph/cleanup/radosnamespace_test.go
  pkg/daemon/ceph/client/image.go
  pkg/daemon/ceph/client/image_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/controller/cleanup.go
  pkg/operator/ceph/controller/cleanup_test.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  tests/framework/clients/block.go
Labels: lgtm

#622 csv: add annotation to make rook non-standalone
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/olm/assemble/metadata-common.yaml
Labels: lgtm

#625 csv: these are missing auto-generated csv changes
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephbucketnotifications.yaml
  build/csv/ceph/ceph.rook.io_cephbuckettopics.yaml
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/csv/ceph/ceph.rook.io_cephcosidrivers.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemmirrors.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystems.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  build/csv/ceph/ceph.rook.io_cephnfses.yaml
  build/csv/ceph/ceph.rook.io_cephobjectrealms.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstoreusers.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzonegroups.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  build/csv/ceph/ceph.rook.io_cephrbdmirrors.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
Labels: lgtm

#626 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/resources.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/client/informers/externalversions/factory.go
  pkg/daemon/ceph/client/subvolumegroup.go
  pkg/daemon/ceph/osd/kms/kmip.go
  pkg/daemon/util/cmdreporter_test.go
  pkg/operator/ceph/controller/cluster_info.go
  pkg/operator/ceph/controller/cluster_info_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
  pkg/operator/ceph/predicate.go
Labels: lgtm

#628 BUG 2275886: Fix OwnerReferences on CSI config map
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/controller/cluster_info.go
  pkg/operator/ceph/controller/cluster_info_test.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/k8sutil/resources.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#633 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/create-external-cluster-resources.py
Labels: lgtm

#634 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-clone.md
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
  deploy/charts/rook-ceph-cluster/values.yaml
  pkg/apis/ceph.rook.io/v1/annotations.go
  pkg/apis/ceph.rook.io/v1/keys.go
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/operator/ceph/cluster/mgr/spec.go
Labels: lgtm

#636 Bug 2276591: csi: create csi configmap if csi controller is disabled
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/controller.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#632 Bug 2273398: osd: Legacy osds on lvm pvcs crash on resize init container
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-urgent

#637 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/CRDs/Cluster/network-providers.md
  Documentation/Getting-Started/example-configurations.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  Documentation/Storage-Configuration/NFS/nfs.md
  cmd/rook/util/cmdreporter.go
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/external/cluster-external.yaml
  deploy/examples/external/common-external.yaml
  deploy/examples/external/create-external-cluster-resources-tests.py
  deploy/examples/external/create-external-cluster-resources.py
  deploy/examples/external/dashboard-external-http.yaml
  deploy/examples/external/dashboard-external-https.yaml
  deploy/examples/external/import-external-cluster.sh
  deploy/examples/external/object-bucket-claim-delete.yaml
  deploy/examples/external/object-external.yaml
  deploy/examples/external/storageclass-bucket-delete.yaml
  deploy/examples/images.txt
  deploy/examples/import-external-cluster.sh
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/daemon/util/cmdreporter.go
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/topology/topology.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  tests/framework/utils/snapshot.go
Labels: lgtm

#639 Syncing latest changes from upstream master for rook
  .github/workflows/golangci-lint.yaml
  .github/workflows/multus.yaml
Labels: lgtm
