Repository red-hat-storage/rook, pull requests merged in 2024-10, with the labels that each got.

#737 Bug 2315733: csi: add sc privileged to logrotate sidecar container
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/csi-logrotate-sidecar.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-unspecified

#736 Syncing latest changes from upstream master for rook
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/linters.yaml
  .github/workflows/mod-check.yml
  .github/workflows/multus.yaml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/scorecards.yml
  .github/workflows/shellcheck.yaml
  .github/workflows/snyk.yaml
  .github/workflows/unit-test.yml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Storage-Configuration/Advanced/ceph-configuration.md
  go.mod
  go.sum
Labels: lgtm

#738 Syncing latest changes from upstream master for rook
  .github/workflows/daily-nightly-jobs.yml
  pkg/daemon/ceph/client/pool.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/csi-logrotate-sidecar.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  tests/scripts/github-action-helper.sh
Labels: lgtm

#739 Bug 2310332: core: Preserve pool application name change
  pkg/daemon/ceph/client/pool.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
Labels: bugzilla/valid-bug, lgtm, bugzilla/severity-high

#740 Syncing latest changes from upstream master for rook
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/controller.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/controller/controller_utils_test.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/cosi/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/discover/discover.go
  tests/framework/installer/ceph_helm_installer.go
Labels: lgtm

#744 Syncing latest changes from upstream master for rook
  pkg/operator/ceph/file/mds/livenessprobe.go
  pkg/operator/ceph/file/mds/livenessprobe.sh
Labels: lgtm

#745 Syncing latest changes from upstream master for rook
  tests/scripts/github-action-helper.sh
Labels: lgtm

#746 Bug 2315624: Fix mds liveness probe and mon failover
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/file/mds/livenessprobe.go
  pkg/operator/ceph/file/mds/livenessprobe.sh
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#749 Syncing latest changes from upstream master for rook
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  .github/workflows/scorecards.yml
  design/ceph/osd-migration.md
  pkg/daemon/multus/resources.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: lgtm

#751 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  Documentation/CRDs/Block-Storage/ceph-block-pool-rados-namespace-crd.md
  Documentation/CRDs/Block-Storage/ceph-rbd-mirror-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  build/csv/ceph/rook-ceph-external-cluster-script-config_v1_configmap.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/radosnamesapce-mirrored.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/mirror.go
  pkg/daemon/ceph/client/mirror_test.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/radosnamespace.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
Labels: lgtm

#752 Bug 2315666: csi: Disable fencing in Rook
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#753 Syncing latest changes from upstream master for rook
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/linters.yaml
  .github/workflows/mod-check.yml
  .github/workflows/multus.yaml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/rgw-multisite-test/action.yml
  .github/workflows/scorecards.yml
  .github/workflows/shellcheck.yaml
  .github/workflows/snyk.yaml
  .github/workflows/unit-test.yml
  tests/scripts/github-action-helper.sh
Labels: lgtm

#754 core: change ceph min version for rbd mirroring
  pkg/daemon/ceph/client/mirror.go
Labels: approved, lgtm

#756 Bug 2319102: core: fix deletion of the osd-replace-config cm
  pkg/operator/ceph/cluster/osd/osd.go
Labels: bugzilla/valid-bug, bugzilla/severity-urgent

#757 Syncing latest changes from upstream master for rook
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md
  deploy/examples/csi/cephfs/pvc.yaml
  deploy/examples/csi/rbd/groupsnapshot.yaml
  deploy/examples/csi/rbd/groupsnapshotclass.yaml
  deploy/examples/csi/rbd/pvc.yaml
  pkg/operator/ceph/cluster/nodedaemon/add.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/nodedaemon/pruner_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
  pkg/operator/ceph/cluster/osd/osd.go
  tests/framework/utils/k8s_helper.go
Labels: lgtm

#758 Syncing latest changes from upstream master for rook
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  deploy/examples/object-separate-pools-test.yaml
  deploy/examples/two-object-one-zone-test.yaml
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/controller/cleanup.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/cosi/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/discover/discover.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
  tests/scripts/collect-logs.sh
  tests/scripts/github-action-helper.sh
Labels: lgtm

#755 Syncing latest changes from master for rook
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/linters.yaml
  .github/workflows/mod-check.yml
  .github/workflows/multus.yaml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/rgw-multisite-test/action.yml
  .github/workflows/scorecards.yml
  .github/workflows/shellcheck.yaml
  .github/workflows/snyk.yaml
  .github/workflows/unit-test.yml
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md
  deploy/examples/csi/cephfs/pvc.yaml
  deploy/examples/csi/rbd/groupsnapshot.yaml
  deploy/examples/csi/rbd/groupsnapshotclass.yaml
  deploy/examples/csi/rbd/pvc.yaml
  pkg/daemon/ceph/client/mirror.go
  pkg/operator/ceph/cluster/nodedaemon/add.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/nodedaemon/pruner_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
  pkg/operator/ceph/cluster/osd/osd.go
  tests/framework/utils/k8s_helper.go
  tests/scripts/github-action-helper.sh
Labels: lgtm

#759 Syncing latest changes from upstream master for rook
  deploy/examples/operator.yaml
Labels: lgtm

#760 Syncing latest changes from master for rook
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  deploy/examples/object-separate-pools-test.yaml
  deploy/examples/operator.yaml
  deploy/examples/two-object-one-zone-test.yaml
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/controller/cleanup.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/cosi/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/discover/discover.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
  tests/scripts/collect-logs.sh
  tests/scripts/github-action-helper.sh
Labels: lgtm

#761 Syncing latest changes from upstream master for rook
  .github/workflows/codegen.yml
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md
  deploy/examples/csi/cephfs/pvc.yaml
  deploy/examples/csi/rbd/groupsnapshot.yaml
  deploy/examples/csi/rbd/groupsnapshotclass.yaml
  deploy/examples/csi/rbd/pvc.yaml
  pkg/operator/ceph/object/json_helpers.go
  pkg/operator/ceph/object/json_helpers_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/shared_pools.go
  pkg/operator/ceph/object/shared_pools_test.go
Labels: lgtm

#762 Syncing latest changes from master for rook
  .github/workflows/codegen.yml
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md
  deploy/examples/csi/cephfs/pvc.yaml
  deploy/examples/csi/rbd/groupsnapshot.yaml
  deploy/examples/csi/rbd/groupsnapshotclass.yaml
  deploy/examples/csi/rbd/pvc.yaml
  pkg/operator/ceph/object/json_helpers.go
  pkg/operator/ceph/object/json_helpers_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/shared_pools.go
  pkg/operator/ceph/object/shared_pools_test.go
Labels: lgtm

#763 Syncing latest changes from upstream master for rook
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  tests/integration/ceph_object_test.go
Labels: lgtm

#769 Syncing latest changes from upstream master for rook
  .github/workflows/scorecards.yml
  Documentation/CRDs/Cluster/external-cluster/advance-external.md
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/CRDs/Cluster/external-cluster/upgrade-external.md
  ROADMAP.md
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm
