Repository red-hat-storage/rook, pull requests merged in 2024-08, with the labels that each got.

#690 Syncing latest changes from upstream master for rook
  .github/workflows/auto-assign.yaml
  .mergify.yml
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/object_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/admin_test.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  pkg/operator/ceph/object/status.go
  pkg/operator/ceph/object/status_test.go
  pkg/operator/ceph/object/user/controller.go
Labels: lgtm

#692 Syncing latest changes from upstream master for rook
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: lgtm

#693 Syncing latest changes from upstream master for rook
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  design/ceph/object/store.md
  go.mod
  go.sum
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/admin_test.go
Labels: lgtm

#696 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-test.yml
  .github/workflows/integration-test-keystone-auth-suite.yaml
Labels: lgtm

#697 Syncing latest changes from upstream master for rook
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .mergify.yml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Upgrade/ceph-upgrade.md
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
Labels: lgtm

#698 Syncing latest changes from upstream master for rook
  .github/workflows/multus.yaml
  .github/workflows/scorecards.yml
  README.md
  go.mod
  go.sum
  tests/scripts/multus/host-cfg-ds.yaml
Labels: lgtm

#700 csv: update capabilities to seamless upgrade
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/olm/assemble/metadata-common.yaml
Labels: lgtm

#699 Syncing latest changes from upstream master for rook
  .github/workflows/auto-assign.yaml
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/linters.yaml
  .github/workflows/mod-check.yml
  .github/workflows/multus.yaml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/snyk.yaml
  .github/workflows/stale.yaml
  .github/workflows/unit-test.yml
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/annotations.go
  pkg/apis/ceph.rook.io/v1/annotations_test.go
  pkg/apis/ceph.rook.io/v1/keys.go
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/apis/ceph.rook.io/v1/labels_test.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/controller_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  pkg/operator/ceph/controller/network.go
  pkg/operator/ceph/controller/version.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
  tests/scripts/csiaddons.sh
Labels: lgtm

#702 Syncing latest changes from upstream master for rook
  .github/workflows/scorecards.yml
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
Labels: lgtm

#707 csv: update the csv in release-4.17 branch
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephbucketnotifications.yaml
  build/csv/ceph/ceph.rook.io_cephbuckettopics.yaml
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/csv/ceph/ceph.rook.io_cephcosidrivers.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemmirrors.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystems.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
  build/csv/ceph/ceph.rook.io_cephnfses.yaml
  build/csv/ceph/ceph.rook.io_cephobjectrealms.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstoreusers.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzonegroups.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  build/csv/ceph/ceph.rook.io_cephrbdmirrors.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
Labels: lgtm

#708 Bug 2306577: external: remove the false bool values from config file
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/invalid-bug, lgtm, bugzilla/severity-medium

#710 Bug 2295778: osd: reweight osd while resizing
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-test.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/ceph/client/osd_test.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/create_test.go
  pkg/operator/ceph/cluster/osd/integration_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
Labels: bugzilla/invalid-bug, bugzilla/severity-high

#709 Syncing latest changes from upstream master for rook
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  cmd/rook/ceph/cleanup.go
  cmd/rook/userfacing/multus/validation/validation.go
  deploy/examples/create-external-cluster-resources.py
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/mon/spec_test.go
  pkg/operator/ceph/csi/peermap/config_test.go
  tests/framework/installer/settings.go
  tests/integration/ceph_upgrade_test.go
  tests/scripts/github-action-helper.sh
  tests/scripts/multus/test-110-cli.sh
  tests/scripts/multus/test-210-stretch-overlap.sh
  tests/scripts/multus/test-220-stretch-pub-and-cluster.sh
  tests/scripts/multus/test-230-stretch-pub-only.sh
  tests/scripts/multus/test-240-stretch-cluster-only.sh
Labels: approved, lgtm

#712 Syncing latest changes from upstream master for rook
  .github/workflows/commitlint.yml
  .github/workflows/scorecards.yml
  .github/workflows/snyk.yaml
  go.mod
  go.sum
Labels: lgtm

#713 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/host-cluster.md
  Documentation/Contributing/development-flow.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
Labels: lgtm
