Repository red-hat-storage/rook, pull requests merged in 2024-02, with the labels that each got.

#565 Bug 2258861: exporter: Don't delete exporter service on daemon deletion
  deploy/examples/create-external-cluster-resources.py
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
  tests/scripts/pythonwebserver/server.py
Labels: bugzilla/valid-bug, approved, bugzilla/severity-urgent

#569 ci: fix detection of GH actions extra disk
  .github/workflows/canary-integration-test.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/encryption-pvc-kms-ibm-kp/action.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/rgw-multisite-test/action.yml
  tests/framework/installer/ceph_manifests.go
  tests/scripts/github-action-helper.sh
Labels: approved, lgtm

#555 Bug 2257371: external: include 255 as a valid ip range
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, bugzilla/severity-medium

#568 Bug 2259668: csi: update network fence CR name
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#570 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md
  Documentation/CRDs/ceph-nfs-crd.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage.md
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster.yaml
  deploy/examples/csi/cephfs/kube-registry.yaml
  deploy/examples/filesystem-ec.yaml
  deploy/examples/filesystem-mirror.yaml
  deploy/examples/filesystem.yaml
  deploy/examples/nfs.yaml
  deploy/examples/object-ec.yaml
  deploy/examples/object-openshift.yaml
  deploy/examples/object.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  deploy/examples/rbdmirror.yaml
  design/ceph/ceph-nfs-ganesha.md
  design/ceph/object/ceph-cosi-driver.md
  design/ceph/resource-constraints.md
  design/common/multiple-storage-types-support.md
  go.mod
  go.sum
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
  pkg/operator/ceph/cluster/watcher.go
  tests/scripts/github-action-helper.sh
Labels: lgtm

#554 Bug 2244609: external: honour support of cluster-name legacy flag
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#572 Bug 2262070: core: remove namespace/ownerRef from networkFence
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/controller_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  pkg/operator/ceph/csi/csi.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#573 Syncing latest changes from upstream master for rook
  .commitlintrc.json
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/common.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/network.go
  pkg/apis/ceph.rook.io/v1/network_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/controller_test.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  tests/scripts/github-action-helper.sh
Labels: lgtm

#574 BUG 2259668: core: Continue processing PVs for network fencing when no node IPs found
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#575 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-suite.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/collect-logs/action.yaml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/encryption-pvc-kms-ibm-kp/action.yml
  .github/workflows/rgw-multisite-test/action.yml
  .mergify.yml
  ROADMAP.md
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  tests/scripts/collect-logs.sh
Labels: lgtm

#576 Syncing latest changes from upstream master for rook
  .github/workflows/daily-nightly-jobs.yml
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  Documentation/CRDs/specification.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  Documentation/Upgrade/ceph-upgrade.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc-minikube.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/crds.yaml
  deploy/examples/import-external-cluster.sh
  deploy/examples/pool-builtin-mgr.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  tests/framework/installer/ceph_manifests.go
Labels: lgtm

#579 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  ROADMAP.md
  build/crds/build-crds.sh
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/volume.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/osd/remove_test.go
  pkg/operator/ceph/cluster/mon/drain.go
  pkg/operator/ceph/cluster/mon/drain_test.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/cluster/mon/spec_test.go
  pkg/operator/ceph/cluster/osd/create_test.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
  pkg/operator/ceph/cluster/osd/integration_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: lgtm

#578 Bug 2265124: csi: remove cephFs networkFence code temporarily
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#580 Syncing latest changes from upstream master for rook
  .commitlintrc.json
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
  cmd/rook/main.go
  go.mod
  go.sum
  pkg/operator/ceph/version/version.go
  tests/framework/installer/ceph_installer.go
  tests/scripts/auto-grow-storage.sh
  tests/scripts/create-dev-cluster.sh
  tests/scripts/github-action-helper.sh
Labels: lgtm
