Repository red-hat-storage/rook, pull requests merged in 2024-01, with the labels that each got.

#551 Bug 2255328: Update minimum ceph version required for ceph-exporter daemon
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#552 Bug 2241268: osd: create config before migration osd
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/osd/daemon.go
Labels: approved, lgtm

#553 Bug 2257296: nfs: enable the rpc liveness probe in d/s 4.15
  pkg/operator/ceph/nfs/spec.go
Labels: approved, bugzilla/invalid-bug, lgtm, bugzilla/severity-unspecified

#557 Bug 2259187: osd: wait for the pgs to be clean
  pkg/operator/ceph/cluster/osd/osd.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#558 Bug 2260279: exporter: Skip reconcile on exporter deletion
  pkg/operator/ceph/controller/predicate.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-medium

#559 Bug 2254547: object: improve the error handling for multisite objs
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  tests/framework/clients/object.go
  tests/integration/ceph_base_object_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high
