Repository red-hat-storage/rook, pull requests merged in 2024-07, with the labels that each got.

#673 Syncing latest changes from master for rook
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: lgtm

#674 Syncing latest changes from upstream master for rook
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/watcher.go
Labels: lgtm

#677 Bug 2296991: pool: Skip updating crush rules for stretch clusters
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
Labels: bugzilla/valid-bug, bugzilla/severity-high

#678 Syncing latest changes from upstream master for rook
  Documentation/Storage-Configuration/Object-Storage-RGW/cosi.md
  PendingReleaseNotes.md
  README.md
  deploy/examples/cosi/bucketaccessclass.yaml
  deploy/examples/cosi/bucketclass.yaml
  deploy/examples/images.txt
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/operator/ceph/object/cosi/controller.go
  pkg/operator/ceph/object/cosi/spec.go
  tests/framework/installer/ceph_manifests.go
Labels: lgtm

#679 Syncing latest changes from upstream master for rook
  .github/workflows/multus.yaml
  Documentation/CRDs/Cluster/network-providers.md
  Makefile
  PendingReleaseNotes.md
  build/deploy/generate-deploy-examples.sh
  cmd/rook/userfacing/multus/validation/validation.go
  deploy/examples/multus-validation-test-openshift.yaml
  deploy/examples/multus-validation.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/daemon/multus/config.go
  pkg/daemon/multus/config.yaml
  pkg/daemon/multus/config_test.go
  pkg/daemon/multus/host-daemonset.yaml
  pkg/daemon/multus/resources.go
  pkg/daemon/multus/templates.go
  pkg/daemon/multus/validation.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/csi-logrotate-sidecar.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  pkg/operator/ceph/csi/util_test.go
  pkg/operator/ceph/pool/controller.go
  tests/scripts/multus/default-public-cluster-nads.yaml
  tests/scripts/multus/host-cfg-ds.yaml
Labels: lgtm

#680 Syncing latest changes from upstream master for rook
  .github/workflows/daily-nightly-jobs.yml
  PendingReleaseNotes.md
  deploy/examples/cluster-test.yaml
  go.mod
  go.sum
  pkg/operator/ceph/cluster/version_test.go
  pkg/operator/ceph/version/version.go
  pkg/operator/ceph/version/version_test.go
  tests/framework/installer/ceph_installer.go
  tests/integration/ceph_upgrade_test.go
Labels: lgtm

#681 csi: fix template render in logRotation
  pkg/operator/ceph/csi/spec.go
Labels: approved, lgtm

#683 Syncing latest changes from upstream master for rook
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  design/ceph-csi-operator.md
  design/ceph/object/store.md
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/predicate.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: lgtm

#649 Bug 2281619: build: update go mod
  .github/workflows/golangci-lint.yaml
  .github/workflows/linters.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: bugzilla/valid-bug, bugzilla/severity-high

#630 BUG 2276533: osd: Legacy osds on lvm pvcs crash on resize init container
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-urgent

#686 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  tests/integration/ceph_upgrade_test.go
Labels: lgtm

#687 Syncing latest changes from upstream master for rook
  Documentation/Troubleshooting/ceph-common-issues.md
Labels: lgtm

#689 Syncing latest changes from upstream master for rook
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/mgr.go
  pkg/daemon/ceph/client/mgr_test.go
Labels: lgtm

#688 Syncing latest changes from master for rook
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/Troubleshooting/ceph-common-issues.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/mgr.go
  pkg/daemon/ceph/client/mgr_test.go
  tests/integration/ceph_upgrade_test.go
Labels: lgtm
