Repository red-hat-storage/rook, pull requests merged in 2024-03, with the labels that each got.

#585 BUG 2265514: csi: update CSIDriverOption params during saving cluster config
  images/ceph/Dockerfile
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-urgent

#582 Syncing latest changes from upstream master for rook
  .github/workflows/build.yml
  .github/workflows/helm-lint.yaml
  Documentation/Getting-Started/Prerequisites/authenticated-registry.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Advanced/key-management-system.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  PendingReleaseNotes.md
  build/csv/csv-gen.sh
  deploy/charts/library/templates/_cluster-serviceaccount.tpl
  deploy/charts/rook-ceph-cluster/templates/securityContextConstraints.yaml
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common-second-cluster.yaml
  deploy/examples/common.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  images/ceph/Dockerfile
  images/ceph/Makefile
  pkg/apis/ceph.rook.io/v1/scc.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/mon/spec_test.go
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/cluster/rbd/spec_test.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mds/spec_test.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/file/mirror/spec_test.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/nfs/spec_test.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
  pkg/operator/k8sutil/k8sutil.go
  tests/framework/installer/ceph_settings.go
  tests/framework/utils/snapshot.go
Labels: lgtm

#566 Bug 2253429: exporter: Don't delete exporter service on daemon deletion
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#586 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/external-cluster.md
  Documentation/CRDs/Cluster/network-providers.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  deploy/charts/rook-ceph-cluster/values.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm

#587 Syncing latest changes from upstream master for rook
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  PendingReleaseNotes.md
Labels: lgtm

#588 Syncing latest changes from upstream master for rook
  Documentation/CRDs/Cluster/external-cluster.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/object.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/integration/ceph_upgrade_test.go
Labels: lgtm

#593 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/.pages
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/external-cluster/.pages
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/CRDs/Cluster/external-cluster/topology-for-external-mode.md
  Documentation/Getting-Started/glossary.md
  ROADMAP.md
  deploy/charts/rook-ceph-cluster/templates/securityContextConstraints.yaml
  deploy/examples/common-external.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/direct-mount.yaml
  deploy/examples/import-external-cluster.sh
  deploy/examples/operator-openshift.yaml
  deploy/examples/toolbox-operator-image.yaml
  deploy/examples/toolbox.yaml
Labels: lgtm

#584 Added new rook bundle creation script
  Dockerfile.bundle
  Makefile
  build/bundle/annotations.yaml
  build/bundle/gen-bundle.sh
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/csv/csv-gen.sh
  deploy/olm/assemble/metadata-common.yaml
Labels: lgtm

#596 csi: update csiaddons/k8s-sidecar image
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/operator-openshift.yaml
Labels: lgtm

#597 build: add new env value ref for operator
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/operator-openshift.yaml
Labels: lgtm

#599 Add all the csi env
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/csv/csv-gen.sh
  deploy/examples/operator-openshift.yaml
  deploy/olm/assemble/metadata-common.yaml
Labels: lgtm

#601 csi: add a new flag to disable csi driver
  Documentation/Helm-Charts/operator-chart.md
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/controller.go
Labels: lgtm

#605 build: add skipRange and replaces to the rook csv
  build/common.sh
  build/csv/csv-gen.sh
Labels: lgtm

#606 csv: update csv version to 4.16
  .commitlintrc.json
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
Labels: lgtm

#609 Syncing latest changes from master for rook
  build/common.sh
  build/csv/csv-gen.sh
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/mgr/drain.go
  pkg/operator/ceph/cluster/mgr/drain_test.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/cluster/mon/drain.go
  pkg/operator/ceph/cluster/mon/drain_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/disruption/clusterdisruption/add.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
  pkg/operator/ceph/disruption/clusterdisruption/pools.go
  pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
  pkg/operator/k8sutil/k8sutil.go
Labels: lgtm

#611 Re-sync upstream release-1.14 to downstream release-4.16
  .github/workflows/build.yml
  Documentation/CRDs/Cluster/external-cluster/topology-for-external-mode.md
  Documentation/Contributing/rook-test-framework.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
  Documentation/Upgrade/rook-upgrade.md
  Makefile
  build/makelib/golang.mk
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/direct-mount.yaml
  deploy/examples/images.txt
  deploy/examples/import-external-cluster.sh
  deploy/examples/multus-validation.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/toolbox-job.yaml
  deploy/examples/toolbox-operator-image.yaml
Labels: lgtm
