Repository red-hat-storage/rook, pull requests merged in 2024-11, with the labels that each got.

#767 multus: remove csi holder pods key
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/operator-openshift.yaml
Labels: approved, lgtm

#771 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
  deploy/examples/crds.yaml
  deploy/examples/radosnamespace-mirrored.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/mirror_health.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/status.go
Labels: approved, lgtm

#775 Syncing latest changes from upstream master for rook
  .github/workflows/scorecards.yml
  go.mod
  go.sum
Labels: approved, lgtm

#776 Update csv version to 4.18
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#777 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/external-cluster/provider-export.md
  pkg/operator/ceph/cluster/osd/spec.go
Labels: approved, lgtm

#774 Syncing latest changes from master for rook
  .github/workflows/scorecards.yml
  Documentation/CRDs/specification.md
  build/common.sh
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
  deploy/examples/crds.yaml
  deploy/examples/radosnamespace-mirrored.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/mirror_health.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/status.go
Labels: approved, lgtm

#778 Syncing latest changes from upstream master for rook
  .github/workflows/docs-check.yml
  .github/workflows/unit-test.yml
  deploy/charts/rook-ceph-cluster/templates/deployment.yaml
  pkg/operator/ceph/cluster/osd/topology/topology.go
Labels: lgtm

#779 Syncing latest changes from master for rook
  .github/workflows/canary-integration-test.yml
  .github/workflows/docs-check.yml
  .github/workflows/unit-test.yml
  Documentation/CRDs/Cluster/external-cluster/provider-export.md
  deploy/charts/rook-ceph-cluster/templates/deployment.yaml
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/topology/topology.go
Labels: approved, lgtm

#773 DFBUGS-825: object: also use system certs for validating RGW cert
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/s3-handlers_test.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#772 DFBUGS-342: object: also use system certs for validating RGW cert
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/s3-handlers_test.go
  tests/scripts/github-action-helper.sh
Labels: approved, jira/valid-reference, jira/valid-bug

#782 Syncing latest changes from master for rook
  .github/workflows/scorecards.yml
  deploy/charts/rook-ceph-cluster/templates/deployment.yaml
  deploy/charts/rook-ceph/templates/deployment.yaml
  design/ceph/ceph-nfs-ganesha.md
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/csi/ceph_connection.go
  pkg/operator/ceph/csi/ceph_connection_test.go
  pkg/operator/ceph/csi/config.go
  pkg/operator/ceph/csi/config_test.go
  pkg/operator/ceph/csi/operator_config.go
  pkg/operator/ceph/csi/operator_config_test.go
  pkg/operator/ceph/csi/operator_driver.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zone/controller_test.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
Labels: approved, lgtm

#783 Syncing latest changes from upstream master for rook
  .mergify.yml
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
Labels: approved, lgtm

#784 Syncing latest changes from upstream master for rook
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/scorecards.yml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/daemon/ceph/client/mirror.go
  pkg/operator/ceph/csi/spec.go
  tests/scripts/csiaddons.sh
Labels: approved, lgtm
