Repository red-hat-storage/rook, pull requests merged in 2025-06, with the labels that each got.

#909 DFBUGS-2645: nfs: remove the nodeid from the server thats not used
  pkg/operator/ceph/nfs/nfs.go
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-important

#914 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  Documentation/Contributing/development-environment.md
  ROADMAP.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/auth.go
  pkg/daemon/ceph/client/mirror_health.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/kms/envs_test.go
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/mgr/config.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/nodedaemon/keyring.go
  pkg/operator/ceph/cluster/osd/volumes_test.go
  pkg/operator/ceph/cluster/rbd/config.go
  pkg/operator/ceph/config/keyring/admin.go
  pkg/operator/ceph/config/keyring/cephx.go
  pkg/operator/ceph/config/keyring/cephx_test.go
  pkg/operator/ceph/config/keyring/store.go
  pkg/operator/ceph/config/keyring/store_test.go
  pkg/operator/ceph/controller/label.go
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/csi/secrets.go
  pkg/operator/ceph/file/mds/config.go
  pkg/operator/ceph/file/mirror/config.go
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/status.go
  tests/scripts/helm.sh
Labels: approved, lgtm

#918 Syncing latest changes from master for rook
  .github/workflows/helm-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Contributing/rook-test-framework.md
  Makefile
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephfilesystems.yaml
  build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
  build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/image.go
  pkg/daemon/ceph/client/image_test.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
  pkg/operator/ceph/file/filesystem_test.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  tests/framework/installer/ceph_installer.go
  tests/framework/installer/environment.go
  tests/integration/ceph_base_keystone_test.go
  tests/scripts/helm.sh
Labels: approved, lgtm

#920 DFBUGS-2744: pool: blocklist rns image watchers
  pkg/daemon/ceph/cleanup/radosnamespace.go
  pkg/daemon/ceph/cleanup/radosnamespace_test.go
  pkg/daemon/ceph/client/image.go
  pkg/daemon/ceph/client/image_test.go
  pkg/daemon/ceph/client/osd.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug, jira/severity-critical

#921 Syncing latest changes from upstream master for rook
  Documentation/Upgrade/ceph-upgrade.md
  Makefile
  pkg/daemon/ceph/osd/remove.go
  pkg/operator/ceph/cluster/osd/osd.go
Labels: approved, lgtm

#923 Syncing latest changes from upstream master for rook
  build/release/Makefile
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/object/user/controller.go
Labels: approved, lgtm

#925 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/crds.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
Labels: approved, lgtm

#927 Syncing latest changes from upstream master for rook
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/unit-test.yml
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  Documentation/Helm-Charts/operator-chart.gotmpl.md
  Documentation/Helm-Charts/operator-chart.md
  PendingReleaseNotes.md
Labels: approved, lgtm

#929 DFBUGS-2880: Provide option to skip csi user and have option in cephClient to provide the secret name
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
  pkg/operator/ceph/csi/secrets.go
  pkg/operator/ceph/csi/secrets_test.go
  pkg/operator/k8sutil/secret.go
  pkg/operator/k8sutil/secret_test.go
Labels: approved, jira/valid-reference, jira/valid-bug, jira/severity-critical
