Repository red-hat-storage/rook, pull requests merged in 2025-07, with the labels that each got.

#930 Syncing latest changes from upstream master for rook
  .github/workflows/scorecards.yml
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
  pkg/operator/ceph/csi/secrets.go
  pkg/operator/ceph/csi/secrets_test.go
  pkg/operator/k8sutil/secret.go
  pkg/operator/k8sutil/secret_test.go
Labels: approved, lgtm

#931 DFBUGS-1501: [4.17]Allow one healthy OSD to be drained.
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc-minikube.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  design/ceph/ceph-managed-disruptionbudgets.md
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/osd.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/disruption/clusterdisruption/add.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
  pkg/operator/ceph/disruption/clusterdisruption/reconcile.go
  tests/framework/installer/ceph_manifests.go
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-critical

#932 Syncing latest changes from upstream master for rook
  Documentation/Contributing/development-environment.md
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/dashboard_test.go
  pkg/operator/ceph/object/realm/controller.go
  tests/scripts/create-dev-cluster.sh
Labels: approved, lgtm

#933 Syncing latest changes from master for rook
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/scorecards.yml
  .github/workflows/unit-test.yml
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  Documentation/Helm-Charts/operator-chart.gotmpl.md
  Documentation/Helm-Charts/operator-chart.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
  pkg/operator/ceph/csi/secrets.go
  pkg/operator/ceph/csi/secrets_test.go
  pkg/operator/k8sutil/secret.go
  pkg/operator/k8sutil/secret_test.go
Labels: approved, lgtm

#934 DFBUGS-2929: core: delete rgw admin user with invalid key
  pkg/operator/ceph/object/user/controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#924 operator: add memory, cpu request and limit values
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/operator-openshift.yaml
Labels: approved, lgtm

#935 DFBUGS-2929: object: retry rgw admin ops InvalidAccessKeyId workaround
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/user/controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#936 Syncing latest changes from upstream master for rook
  .github/workflows/tmate_debug/action.yml
  deploy/examples/operator.yaml
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/mon/spec_test.go
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/spec.go
Labels: approved, lgtm

#937 Syncing latest changes from upstream master for rook
  .github/workflows/scorecards.yml
  .github/workflows/snyk.yaml
  pkg/daemon/discover/discover.go
  pkg/operator/discover/discover.go
  pkg/operator/discover/discover_test.go
Labels: approved, lgtm

#939 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-test.yml
  build/release/Makefile
  deploy/examples/cluster.yaml
  design/ceph/ceph-cluster-cleanup.md
  pkg/daemon/ceph/cleanup/disk.go
  pkg/daemon/ceph/cleanup/disk_test.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/remove.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  tests/scripts/github-action-helper.sh
Labels: approved, lgtm

#941 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore-httproute.yaml
  deploy/charts/rook-ceph-cluster/templates/httproute.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
  pkg/operator/ceph/pool/controller.go
  tests/framework/installer/ceph_helm_installer.go
Labels: approved, lgtm

#946 Syncing latest changes from master for rook
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
  Documentation/CRDs/specification.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  PendingReleaseNotes.md
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/release/Makefile
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore-httproute.yaml
  deploy/charts/rook-ceph-cluster/templates/httproute.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  design/ceph/ceph-cluster-cleanup.md
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/cleanup/disk.go
  pkg/daemon/ceph/cleanup/disk_test.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/remove.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
  pkg/operator/ceph/pool/controller.go
  tests/framework/installer/ceph_helm_installer.go
  tests/scripts/github-action-helper.sh
Labels: approved, lgtm

#945 Syncing latest changes from upstream master for rook
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/templates/securityContextConstraints.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/config.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/config/probes.go
  pkg/operator/ceph/config/probes_test.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/status.go
  pkg/util/exec/exec_pod.go
Labels: approved, lgtm

#947 Syncing latest changes from master for rook
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephclients.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/templates/securityContextConstraints.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/config.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/config/probes.go
  pkg/operator/ceph/config/probes_test.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/status.go
  pkg/util/exec/exec_pod.go
Labels: approved, lgtm

#949 csv: update csv to 4.20
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
Labels: approved, lgtm
