Repository red-hat-storage/rook, pull requests merged in 2025-01, with the labels that each got.

#799 DFBUGS-1028: csi-snapshotter flag typo; upgrade csi-snapshotter
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  tests/framework/utils/snapshot.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#794 DFBUGS-978: csi: disable fencing in Rook
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#802 DFBUGS-1299: external: fix rados namespace sc name
  build/csv/ceph/rook-ceph-external-cluster-script-config_v1_configmap.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
Labels: lgtm, jira/valid-reference, jira/valid-bug

#800 DFBUGS-978: Revert "csi: disable fencing in Rook"
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, lgtm, jira/valid-reference, jira/invalid-bug

#803 csv: use ROOK_CSI_ENABLE_CEPHFS in rook operator env
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/examples/operator-openshift.yaml
Labels: lgtm

#806 Manual sync of upstream to downstream
  .github/workflows/commitlint.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/linters.yaml
  .github/workflows/multus.yaml
  .github/workflows/scorecards.yml
  .github/workflows/shellcheck.yaml
  .mergify.yml
  .yamllint
  ADOPTERS.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
  Makefile
  PendingReleaseNotes.md
  ROADMAP.md
  build/csv/ceph/rook-ceph-external-cluster-script-config_v1_configmap.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/makelib/golang.mk
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/images.txt
  deploy/examples/import-external-cluster.sh
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  go.mod
  go.sum
  images/ceph/Makefile
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/client/pool_test.go
  pkg/daemon/ceph/client/upgrade.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/nodedaemon/pruner_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
  pkg/operator/ceph/config/monstore.go
  pkg/operator/ceph/csi/operator_driver.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  tests/integration/ceph_object_test.go
  tests/scripts/multus/host-cfg-ds.yaml
  tests/scripts/validate_modified_files.sh
Labels: lgtm

#807 Syncing latest changes from upstream master for rook
  .github/workflows/build.yml
  .github/workflows/codegen.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/mod-check.yml
  .github/workflows/multus.yaml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/scorecards.yml
  .github/workflows/stale.yaml
  .github/workflows/unit-test.yml
  ADOPTERS.md
  go.mod
  go.sum
Labels: lgtm

#809 Syncing latest changes from upstream master for rook
  Documentation/Helm-Charts/operator-chart.md
  Makefile
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/node.go
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/cluster/osd/topology/topology.go
  pkg/operator/ceph/cluster/osd/topology/topology_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/csi/util.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/k8sutil/labels.go
  pkg/operator/k8sutil/node.go
  pkg/operator/k8sutil/node_test.go
Labels: approved, lgtm
