Repository red-hat-storage/rook, pull requests merged in 2025-04, with the labels that each got.

#853 csv: update rook csv version to 4.19
  build/common.sh
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
Labels: lgtm

#857 rgw: remove v20 check for rgw-readaffinity
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
Labels: lgtm

#863 Syncing latest changes from upstream master for rook
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph-cluster/templates/_helpers.tpl
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore-ingress.yaml
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: lgtm

#867 Syncing latest changes from upstream master for rook
  .github/workflows/canary-integration-test.yml
  Makefile
  pkg/daemon/ceph/client/mirror_health.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/predicate.go
  pkg/operator/ceph/controller/finalizer.go
  pkg/operator/ceph/controller/finalizer_test.go
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/controller_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/topic/controller.go
  pkg/operator/ceph/object/topic/controller_test.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zone/controller_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
  pkg/operator/ceph/pool/status.go
  tests/scripts/github-action-helper.sh
Labels: lgtm

#870 core: update cephstatus fsmap gid type to uint64
  pkg/daemon/ceph/client/status.go
  pkg/daemon/ceph/client/status_test.go
Labels: lgtm

#859 DFBUGS-1912: [release 4.18] core: CVE-2025-30204: rook-ceph-operator-container: jwt-go allows excessive memory allocation during header parsing
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#861 DFBUGS-1909: [release 4.16] core: cve 2025 30204 rook-ceph-operator-container: jwt-go allows excessive memory allocation during header parsing
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#860 DFBUGS-1911: [release 4.17] core: CVE-2025-30204: rook-ceph-operator-container: jwt-go allows excessive memory allocation during header parsing
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#862 DFBUGS-1975: [release 4.18] core: cve 2024 45337- Upgrade to version golang.org/x/crypto-v0.31.0
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#868 DFBUGS-1695: build: update go/jose version to v4.0.5
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#869 DFBUGS-1694: build: update go/jose version to v4.0.5
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#866 DFBUGS-1971: [release 4.18] ci: update golang.org/x/net to 0.33
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#865 DFBUGS-2089: rbdmirror: fix the rados namespace health checkup
  pkg/daemon/ceph/client/mirror_health.go
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-critical

#876 Syncing latest changes from upstream master for rook
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .mergify.yml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/host-cluster.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/CRDs/Cluster/stretch-cluster.md
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  Documentation/Upgrade/ceph-upgrade.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  design/ceph/ceph-cluster-cleanup.md
  go.mod
  go.sum
  images/ceph/Makefile
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/daemon/ceph/client/status.go
  pkg/daemon/ceph/client/status_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
  pkg/util/exec/exec_test.go
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
Labels: lgtm

#743 DFBUGS-714: core: fix reading flags in cleanup job cmd
  .github/workflows/build.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/codegen.yml
  .github/workflows/codespell.yaml
  .github/workflows/commitlint.yml
  .github/workflows/crds-gen.yml
  .github/workflows/create-tag.yaml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/mod-check.yml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/stale.yaml
  .github/workflows/unit-test.yml
  cmd/rook/ceph/cleanup.go
Labels: lgtm, bugzilla/severity-medium, jira/valid-reference, jira/valid-bug

#882 DFBUGS-2015: build: update oauth2 pkg to latest version
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug
