Repository red-hat-storage/rook, pull requests merged in 2025-02, with the labels that each got.

#813 Syncing latest changes from upstream master for rook
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
  deploy/examples/csi-operator.yaml
Labels: lgtm

#815 Syncing latest changes from upstream master for rook
  .github/workflows/docs-check.yml
  .github/workflows/helm-lint.yaml
  .github/workflows/linters.yaml
  .github/workflows/push-build.yaml
  .github/workflows/scorecards.yml
Labels: lgtm

#817 Syncing latest changes from upstream master for rook
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
  build/csv/ceph/rook-ceph-external-cluster-script-config_v1_configmap.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
  deploy/examples/create-external-cluster-resources.py
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
  pkg/operator/ceph/object/bucket/rgw-handlers_test.go
  pkg/operator/ceph/object/bucket/util.go
  tests/integration/ceph_object_test.go
  tests/integration/object/bucketowner/bucketowner.go
Labels: lgtm

#820 Syncing latest changes from upstream master for rook
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm

#823 DFBUGS-1257: ci: update golang.org/x/net to 0.33
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: jira/valid-reference, jira/valid-bug

#821 DFBUGS-1256: ci: update golang.org/x/net to 0.33
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#827 Syncing latest changes from upstream master for rook
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
Labels: lgtm

#825 Syncing latest changes from master for rook
  .github/workflows/build.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/linters.yaml
  .github/workflows/push-build.yaml
  .github/workflows/scorecards.yml
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
  build/csv/ceph/rook-ceph-external-cluster-script-config_v1_configmap.yaml
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  build/csv/csv-gen.sh
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
  deploy/examples/create-external-cluster-resources.py
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
  pkg/operator/ceph/object/bucket/rgw-handlers_test.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
  tests/integration/ceph_object_test.go
  tests/integration/object/bucketowner/bucketowner.go
Labels: lgtm

#829 DFBUGS-848: [release-4.18] manifest: add list and watch capabilities to provisioners
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-critical

#828 Syncing latest changes from upstream master for rook
  .github/workflows/push-build.yaml
  Documentation/Helm-Charts/operator-chart.md
  ROADMAP.md
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  deploy/charts/rook-ceph-cluster/templates/NOTES.txt
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore-ingress.yaml
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
Labels: lgtm

#831 Syncing latest changes from upstream master for rook
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/controller.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/controller/controller_utils_test.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  tests/framework/installer/ceph_settings.go
Labels: lgtm

#832 Syncing latest changes from upstream master for rook
  .github/workflows/golangci-lint.yaml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/host-cluster.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/CRDs/Cluster/stretch-cluster.md
  Documentation/Getting-Started/Prerequisites/authenticated-registry.md
  Documentation/Upgrade/ceph-upgrade.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster-test.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  design/ceph/ceph-cluster-cleanup.md
  pkg/daemon/ceph/client/upgrade.go
  pkg/daemon/ceph/client/upgrade_test.go
  tests/integration/ceph_base_keystone_test.go
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
Labels: lgtm

#833 Syncing latest changes from upstream master for rook
  .github/workflows/build.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/helm-lint.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/scorecards.yml
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: lgtm

#836 DFBUGS-978: Reapply "csi: disable fencing in Rook"
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: lgtm, jira/valid-reference, jira/valid-bug

#835 DFBUGS-979: Reapply "csi: disable fencing in Rook"
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#834 DFBUGS-980: Reapply "csi: disable fencing in Rook"
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#839 DFBUGS-1696: mgr: Wait for builtin mgr pool to exist before enabling stretch
  build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/controller/controller_utils_test.go
  pkg/operator/ceph/file/controller_test.go
  pkg/operator/ceph/object/objectstore.go
  tests/scripts/multus/host-cfg-ds.yaml
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-important
