Repository red-hat-storage/rook, pull requests merged in 2025-05, with the labels that each got.

#883 DFBUGS-1973: build: update go dep x/oauth and x/net
  build/makelib/golang.mk
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: lgtm, jira/valid-reference, jira/valid-bug

#885 DFBUGS-2415: Add more deletion conditions to blockpool and radosnamespace status
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/namespace.go
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/mirror.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/radosnamespace.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/dependents.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
  pkg/operator/ceph/reporting/reporting.go
  pkg/operator/ceph/reporting/status.go
  pkg/operator/ceph/reporting/status_test.go
  pkg/util/dependents/dependents.go
Labels: jira/valid-reference, jira/valid-bug

#887 DFBUGS-965: osd: osd should watch for pvc resize
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
  pkg/operator/k8sutil/pvc.go
  pkg/operator/k8sutil/pvc_test.go
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate

#886 DFBUGS-2460: rbdmirror: fix mirroring status on pool and rn
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/mirror.go
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate

#889 Manual sync from u/p master to d/s master
  .github/workflows/build.yml
  .github/workflows/checkmake.yaml
  .github/workflows/codegen.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/mod-check.yml
  .github/workflows/multus.yaml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/unit-test.yml
  .mergify.yml
  Documentation/CRDs/specification.md
  build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
  build/csv/ceph/ceph.rook.io_cephblockpools.yaml
  build/csv/ceph/ceph.rook.io_cephclusters.yaml
  build/release/Makefile
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/namespace.go
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/mirror.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/radosnamespace.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/dependents.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
  pkg/operator/ceph/reporting/reporting.go
  pkg/operator/ceph/reporting/status.go
  pkg/operator/ceph/reporting/status_test.go
  pkg/operator/k8sutil/pvc.go
  pkg/operator/k8sutil/pvc_test.go
  pkg/util/dependents/dependents.go
Labels: lgtm

#892 DFBUGS-2309: Remove duplicate svg rns cr
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
Labels: approved, lgtm, jira/valid-reference, jira/valid-bug

#894 Syncing latest changes from upstream master for rook
  .github/workflows/docs-check.yml
  .github/workflows/push-build.yaml
  .github/workflows/scorecards.yml
  .golangci.yaml
  pkg/daemon/util/cmdreporter.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
  pkg/operator/test/spec.go
  tests/framework/clients/block.go
  tests/framework/clients/bucket.go
  tests/framework/clients/client.go
  tests/framework/clients/object.go
  tests/framework/utils/env.go
  tests/framework/utils/helm_helper.go
  tests/framework/utils/k8s_helper.go
  tests/integration/object/bucketowner/bucketowner.go
Labels: approved, lgtm

#897 DFBUGS-2586: nfs: fix nfs config file 4.18
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/nfs/config_test.go
  pkg/operator/ceph/nfs/nfs.go
  pkg/operator/ceph/nfs/spec.go
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-important

#900 DFBUGS-2586: Revert "nfs: fix nfs config file"
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/nfs/config_test.go
  pkg/operator/ceph/nfs/nfs.go
  pkg/operator/ceph/nfs/spec.go
Labels: jira/valid-reference, jira/valid-bug, jira/severity-important
